### ISSUE TITLE
自定义背景

### ISSUE THREAD

**Issue by mashirozx** [mashirozx/Sakura#10]
顺带重写一下切换函数，大工程~

**Comment by spirit1431007** [comment]
切换主题时选择 bing每日一图 和 夜间模式 会出现背景填不满屏幕而重复填充的情况（与设备屏幕大小有关）

**Comment by mashirozx** [comment]
> 不知道这个有没有增加呀，希望可以用自己的图片API
> 比如
> http://n1.likeqi.cn:8888/jth/randomimg1/index.php

https://github.com/mashirozx/Sakura/blob/master/js/sakura-app.js#L276
这部分一两百行代码准备重构，一直懒得搞的说。。你可以先换成自己的 url 吧
