### ISSUE TITLE
lib.js过大，是否可以精简

### ISSUE THREAD

**Issue by enjoyuruf** [mashirozx/Sakura#109]
昨日清了缓存，访问自己网站的时候第一屏卡了好一会才出来，看控制台好像是lib.js拖累了速度。
看了看`cdn/js/src/`
其中最大的两个文件`materialize.min.js`不知道是用在了哪里，`hls.js`好像是播放视频用的。
因为我的第一屏没有视频，我尝试把它们删除运行了`do.py`，`lib.js`一下子小了一半。
我删除缓存，查看页面，没有出什么问题。
不过这也和我网站没什么东西有关，很担心后续会有大问题出现，所以来请教mashirozx。
`materialize.min.js`实在是不清楚，但是`hls.js`可以脱离lib.js，让需要第一屏放视频的人额外加载。

**Comment by mashirozx** [comment]
materialize可以移除。七百多k我觉得没多大吧，从jsdelivr加载很快的

**Comment by enjoyuruf** [comment]
感谢回复，虽然的确也不慢，但是网页加载的东西总是越少越好。
