### ISSUE TITLE
English version

### ISSUE THREAD

**Issue by dausruddin** [mashirozx/Sakura#112]
I don't understand Chinese. Is it possible to have an English version of it?
Thanks

**Comment by rieval** [comment]
Good idea.

**Comment by mashirozx** [comment]
Well, it is not a difficult work, but there are too many details to fix, the multi-lingualization need some time.

**Comment by ookangzheng** [comment]
If you need help I can help and I speak Chinese

**Comment by mashirozx** [comment]
This work is on agenda. And a very small part of translation is here e64a80c6106004eb26b74dbfa86e5e55da0af660.
 
Chinese speaker is welcomed to contribute at the current stage.

翻译计划已经安排，具体可见 <https://github.com/mashirozx/Sakura/projects/1> 欢迎各位帮忙！

**Comment by mashirozx** [comment]
English translation have done in [v3.2.8](https://github.com/mashirozx/Sakura/releases/tag/v3.2.8).

PR welcome for any improvement in translations.
