### ISSUE TITLE
在safari下首页title错位为两行。

### ISSUE THREAD

**Issue by samondlee** [mashirozx/Sakura#114]
**描述问题**

**bug 重现步骤**

**截图（如有）**

![15702390935761345168926875710201](https://user-images.githubusercontent.com/8521327/66247737-f0839300-e752-11e9-9fbc-14c11a1e35d7.jpg)

**系统信息**
 - （前端）操作系统: [e.g. Windows 10, Android 9.0]
 - 浏览器: [e.g. chrome, safari]
 - PHP 版本
 - WordPress 版本
 - Sakura 主题版本

**补充信息**

**Comment by samondlee** [comment]
地址aHR0cCUzQS8vbjEudXNzLm1vZSUzQTgz

**Comment by samondlee** [comment]
主题没有修改过

**Comment by mashirozx** [comment]
文字太长了，建议添加自定义 css，可以固定容器宽度或者指定 `white-space: nowrap`

**Comment by mashirozx** [comment]
Be free to reopen again 😄
