### ISSUE TITLE
评论markdown无法解析

### ISSUE THREAD

**Issue by haojie06** [mashirozx/Sakura#115]
**描述问题**
评论区使用markdown书写发现并没有起效果 *另外电脑端使用分享到QQ群的功能会无限登陆中*
**bug 重现步骤**
在评论区尝试使用markdown书写，发现并没有起效果
**截图（如有）**
![](https://haojie-storage.oss-cn-shenzhen.aliyuncs.com/haojie/735b91020011945.png)
![image.png](https://haojie-storage.oss-cn-shenzhen.aliyuncs.com/haojie/1712e1020012247.png)
**系统信息**https://guides.github.com/features/mastering-markdown/
 - （前端）操作系统: [e.g. Windows 10, Android 9.0]
 - 浏览器: chrome
 - PHP: 7.2
 - WordPress: 5.2.4
 - Sakura 3.2.6

**补充信息**

**Comment by enjoyuruf** [comment]
你有安装markdown的插件并且勾选评论支持markdown吗？作者的主题说明中有提到。

**Comment by haojie06** [comment]
我使用的是WP Githuber MD，这个插件有支持评论markdown的功能，也打开了，不过没见生效

**Comment by enjoyuruf** [comment]
信息太少了，恐怕作者也给不了什么帮助。
作者对于文档中以外的插件是不保证兼容的。
这边建议更换插件试试。
此外，必须是先启用插件（支持评论），再评论才可以呦。

**Comment by haojie06** [comment]
在我把插件换成WP Editor MD之后新评论有效果了，之前遇到的和代码高亮冲突的情况也没有再出现，谢谢了
