### ISSUE TITLE
友链css样式出现问题，已经修复并附上解决方法

### ISSUE THREAD

**Issue by MoeCrafts** [mashirozx/Sakura#116]
主题版本已经是最新了，但是添加友链的时候发现有如下的问题
![alt bug](https://www.yoshino.ac.cn/wp-content/uploads/2019/10/AZSK5PYXQKIZXRU@3PO.png
)
和作者的代码样式对比之后，发现缺少标签以及对应的样式，修复方法如下：

`#./function.php 第551行`
`$result .=  '<h3 class="link-title">'.$linkcat->name.'</h3>';`
`#修改为`
`$result .=  '<h3 class="link-title"><span class="fake-title">'.$linkcat->name.'</span></h3>';`

`#./style.css 2984行`
`border-left: 3px solid orange;`
`#修改为`
`border-left: none;`

`#文档末尾添加`
`.link-title span.fake-title {`
`    padding-left: 10px;`
`    border-left: 3px solid orange;`
`}`

然后请到外观-Sakura主题设置-CDN
勾选上_本地调用主题 js、css 文件（sakura-app.js、style.css）_

如果你有缓存插件或者CDN，也请更新

**Comment by mashirozx** [comment]
@spirit1431007 似乎是 82ce5b8 导致的问题哟

**Comment by spirit1431007** [comment]
> @spirit1431007 似乎是 [82ce5b8](https://github.com/mashirozx/Sakura/commit/82ce5b80d66ab1bb8ac40b408d9a35686c72ec9b) 导致的问题哟

了解，马上修复

**Comment by mashirozx** [comment]
@spirit1431007 Thanks:kissing_heart:
