### ISSUE TITLE
文章显示更新时间

### ISSUE THREAD

**Issue by haojie06** [mashirozx/Sakura#117]
目前文章列表只显示文章的发布时间，希望能够加入最近一次编辑时间的显示。
这样访客可以比较直观的看出一篇文章最近有没有更新，如下图
![](https://haojie-storage.oss-cn-shenzhen.aliyuncs.com/haojie/82d851025121853.png)

**Comment by mashirozx** [comment]
使用get_post_modified_time()函数不难实现，可DIY
<https://codex.wordpress.org/Function_Reference/get_post_modified_time>

**Comment by mashirozx** [comment]
如果你有好的设计方案，欢迎PR～

**Comment by haojie06** [comment]
谢谢，我会试一试的。
