### ISSUE TITLE
I don't know how to use it

### ISSUE THREAD

**Issue by hifocus** [mashirozx/Sakura#12]
I tried to switch the my blog's theme to Sakura tonight, but I met errors when I just got the theme installed.

I've switched it back to my original theme, but you may see the error at https://testing.hxco.de

Firstly, the cover image cannot be displayed normally.

Secondly, the page cannot be scroll at all, and only the first article can be displayed.

Finally, if you enter any of the blog's article links, you can only see the article's title.

Nothing in the console, no `404` or `403` errors.

![image](https://user-images.githubusercontent.com/30528433/43462280-44a3fd56-9508-11e8-9546-8ac8a2cfecae.png)

Version `3.0.6`, under Lao Xue Hosts US Plan, cPanel Web Hosting.

**Comment by mashirozx** [comment]
Not sure what's wrong with your configuration, but it do works on my [demo site](https://sakura.2heng.xin/). And [this](https://share.2heng.xin/index.php?share/file&user=1&sid=9FVfpIx3) is all the demo site configuration files. Please double check your configuration.

**Comment by hifocus** [comment]
I believe it might be some js files cannot be loaded normally. I will keep my error site and if you have time you can always have a look. It is just the most common config, none of the other themes used to have issues on this. It's really strange.

**Comment by mashirozx** [comment]
![image](https://user-images.githubusercontent.com/16148054/43466453-26a7244a-9512-11e8-921f-888fb6a4f1cb.png)

This is your page source. Seems you do not have the must installed plugin WP-Statistics. You should turn on showing PHP error info for more detail.

**Comment by hifocus** [comment]
Do I HAVE to install WP-Statistics? If the theme relies on this plugin this much, you will need to put it inside your theme.

**Comment by mashirozx** [comment]
you can you up

**Comment by hifocus** [comment]
I have no ill intentions. Just for advise.

**Comment by mashirozx** [comment]
Thanks for your advice, but this is originally a self-used theme. I'll consider this issue latter.

**Comment by Jingyi21** [comment]
If you use Lao Xue Host,Please switch your PHP version →7.1+

Lao Xue Host default PHP version is 5.6

**Comment by hifocus** [comment]
Yes my php version is 7.0 or higher
