### ISSUE TITLE
搜索结果页面显示异常

### ISSUE THREAD

**Issue by haojie06** [mashirozx/Sakura#125]
**描述问题**
搜索结果页面标题位置错误
**bug 重现步骤**
无论是在手机上还是电脑上（Chrome等多个浏览器）搜索时，标题“关于xxx的搜索结果显示位置错误”
**截图（如有）**
![](https://haojie-storage.oss-cn-shenzhen.aliyuncs.com/haojie/af2201110011611.png)
**系统信息**
 - （前端）操作系统: [e.g. Windows 10, Android 9.0]
 - 浏览器: [e.g. chrome, safari]
 - PHP 版本 7.3 
 - WordPress 版本 5.2.4
 - Sakura 主题版本 3.2.8

**补充信息**
查看 theme.plus.php文件，代码如下 ![](https://haojie-storage.oss-cn-shenzhen.aliyuncs.com/haojie/526411110011821.png
)

在chrome中f12查看，发现这个标题处于这个位置
![image](https://user-images.githubusercontent.com/32638818/68532443-21f60c80-0358-11ea-9af2-945e4e581843.png)

而正常的位置显示的是一个数字
![image](https://user-images.githubusercontent.com/32638818/68532461-481bac80-0358-11ea-96d8-e46dbca16274.png)

**Comment by mashirozx** [comment]
@spirit1431007 出来背锅😎

**Comment by spirit1431007** [comment]
[81cd85f](https://github.com/mashirozx/Sakura/commit/dd40809adf28b762ad4ab1b91909b60b178e1cc1) 已解决

**Comment by haojie06** [comment]
好的👌，另外提个小建议
- 现在手机版的文章页面不显示标签，希望之后能够显示
