### ISSUE TITLE
WP 5.3 兼容

### ISSUE THREAD

**Issue by mashirozx** [mashirozx/Sakura#134]
每次 WordPress 更新之后都担心主题出先兼容性问题，之前小改一下都能解决，可这次问题太多了，改不动了。

最近在重构主题，因此我的工作重心是放在重构版上，旧版这边仅仅是时不时地添加一些探索性的功能，bug 修复还等各位 PR 吧。

如果没有 PR 处理 WP 5.3 的兼容性问题的话，我的建议是暂时不要更新 5.3，如果已经更新了的可以考虑[用这个插件](https://wordpress.org/plugins/wp-downgrade/)降级，降到上一版 `5.2.4`，<https://2heng.xin> 就是用这个插件从 5.3 降到 5.2.4 的，请放心。

**Comment by mashirozx** [comment]
已知问题：
1、登陆界面样式崩坏：预估修复难度不高，但懒得修；
2、部分旧的文章 404：就算换成 Twenty Twenty，问题依然存在，应该是 WP 的问题；
3、WP 废弃了几个函数，需要根据 PHP 报错修复。

**Comment by spirit1431007** [comment]
> 已知问题：
> 1、登陆界面样式崩坏：预估修复难度不高，懒得修；
> 2、部分旧的文章 404：就算换成 Twenty Twenty，问题依然存在，应该是 WP 的问题；
> 3、WP 废弃了几个函数：需要根据 PHP 报错修复；
> 4、后台 jQuery 未加载：原因未知；
> 5、Sakura 主题设置界面崩坏：原因未知。

我只复现了1和5，5重启数据库（刷新数据库缓存）后解决
