### ISSUE TITLE
文章只显示标题不显示正文

### ISSUE THREAD

**Issue by DavinciEvans** [mashirozx/Sakura#140]
**描述问题**
页面上只显示标题但是正文不显示，删除一些随机文字之后又可以显示
**bug 重现步骤**
在写完一篇文章之后发布，但文章内容不显示（如下图）。最初我以为是文章问题，将我前几个月写的文章（篇幅内容差不多）复制粘贴过来又可以正常显示。
关闭所有插件之后问题依然存在。
在RSS订阅中能正常显示文章内容，更换到其他主题之后也可以正常显示文章的内容。
这个问题在几个月之前就已经存在了。
**截图（如有）**
![QQ截图20191123192116.png](https://i.loli.net/2019/11/23/mVwbQzkta5sfC9o.png)
![QQ截图20191123192054.png](https://i.loli.net/2019/11/23/RZX5zcsIoP7raNg.png)
**系统信息**
 - （前端）操作系统: win10
 - 浏览器: chrome
 - PHP 版本 PHP 7.2
 - WordPress 版本 5.24
 - Sakura 主题版本 3.2.0

**补充信息**
文章网址：http://davincievans.top/ttrss-install.html

**Comment by spirit1431007** [comment]
使用最新版主题是否还遇到同样问题？

**Comment by mashirozx** [comment]
请更新到最新版主题，看问题是否还存在
<https://github.com/mashirozx/Sakura/releases/latest>

**Comment by DavinciEvans** [comment]
嗯，更新之后貌似没有了，感谢😘
