### ISSUE TITLE
请问一下rss的订阅功能有吗，有的话哪里配置啊

### ISSUE THREAD

**Issue by yah0130** [mashirozx/Sakura#145]
请问一下rss的订阅功能有吗，有的话哪里配置啊

**Comment by spirit1431007** [comment]
WP自带了这个功能，具体的订阅链接可参照 https://wordpress.org/support/article/wordpress-feeds/

**Comment by yah0130** [comment]
> WP自带了这个功能，具体的订阅链接可参照 https://wordpress.org/support/article/wordpress-feeds/

嗯嗯解决了谢谢
