### ISSUE TITLE
QQ头像接口返回QQ昵称为锟斤拷

### ISSUE THREAD

**Issue by EkklesN** [mashirozx/Sakura#146]
**描述问题**
评论部分的QQ头像接口返回QQ昵称为锟斤拷
**bug 重现步骤**

**截图（如有）**
（不好截图，随便输入一个QQ号都是乱码）
**系统信息**
 - （前端）操作系统: [e.g. Windows 10, Android 9.0]
 - 浏览器: Chrome 78.0.3904.108
 - PHP 版本 7.3.11
 - WordPress 版本 5.3
 - Sakura 主题版本 3.3.2

**补充信息**

**Comment by spirit1431007** [comment]
了解，之后将会整合接口到rest api #133

**Comment by mashirozx** [comment]
是腾讯那边的接口 GBK->UTF8 转码出错了，如果腾讯不修复只能另寻接口了。

<https://users.qzone.qq.com/fcg-bin/cgi_get_portrait.fcg?uins=10001>

**Comment by mashirozx** [comment]
API源码
```php
$qq = isset($_GET['qq']) ? addslashes(trim($_GET['qq'])) : '';
if(!empty($qq) && is_numeric($qq) && strlen($qq) > 4 && strlen($qq) < 13){
  $qqnickname = file_get_contents('https://users.qzone.qq.com/fcg-bin/cgi_get_portrait.fcg?uins='.$qq); // API
  if($qqnickname){
    $qqnickname = mb_convert_encoding($qqnickname, "UTF-8", "GBK");
    echo $qqnickname;
  }
}
```
之所以一直没有放进主题里面是因为海外服务器无法访问腾讯的接口，需要国内服务器或者修改hosts

**Comment by spirit1431007** [comment]
> 是腾讯那边的接口 GBK->UTF8 转码出错了，如果腾讯不修复只能另寻接口了。
> 
> https://users.qzone.qq.com/fcg-bin/cgi_get_portrait.fcg?uins=10001

http://r.qzone.qq.com/fcg-bin/cgi_get_portrait.fcg?g_tk=1518561325&uins=10001

**Comment by mashirozx** [comment]
接口已改为内置 8d0bbcd56aa649183fab0616ae7ca0df6f45e664

**Comment by mashirozx** [comment]
可以完善一下 https://github.com/mashirozx/Sakura/blob/dev/inc/api.php#L51
