### ISSUE TITLE
WordPress database error: [Duplicate column name 'comment_markdown'] ALTER TABLE wp_comments ADD comment_markdown text

### ISSUE THREAD

**Issue by mashirozx** [mashirozx/Sakura#152]
> WordPress database error: [Duplicate column name 'comment_markdown']
ALTER TABLE wp_comments ADD comment_markdown text

![image](https://user-images.githubusercontent.com/16148054/70324596-deb18f80-186a-11ea-92d5-7219347240b4.png)

cc: @spirit1431007

**Comment by spirit1431007** [comment]
fixed in https://github.com/mashirozx/Sakura/commit/23088bfc2b58410befd8388567796dcd6b790d51#diff-78cd5aa3783a74555c9938a2a81d01c6R1657
