### ISSUE TITLE
Class::comment_meta()

### ISSUE THREAD

**Issue by mashirozx** [mashirozx/Sakura#154]
https://developer.wordpress.org/reference/functions/get_comment_meta/

直接读写并改变 `wp_comments` 表格的数据结构可能不太符合 wp 开发规范。

**Comment by spirit1431007** [comment]
虽然可以这样，但是我觉得把`comment_content`和`comment_markdown`放一起比较好比对。

**Comment by mashirozx** [comment]
重构版中我会改用 mate 储存的，后续还准备加入点赞并按点赞数排序功能，wp 提供了按 mate 排序输出的方法。
