### ISSUE TITLE
大佬,主题在文章页面打开播放器有空白块

### ISSUE THREAD

**Issue by qwqoo** [mashirozx/Sakura#157]
安装主题后点开文章页在加载时会出现一个空白块,然后消失了,点开右下角播放器也会出现一个空白框 
按F12 的话会有一个空的`aside`标签,我定位不到这个标签的位置.....
环境是nginx+php7.3 wordpress5.3 最新版的主题
在我本地测试和服务器上都会出现这个状况 ,大佬能不能修修呢...
![QQ截图20191213111613](https://user-images.githubusercontent.com/44497002/70767454-5c5e2980-1d9c-11ea-9935-82e8fa47210f.png)
![20191213113437](https://user-images.githubusercontent.com/44497002/70767512-95969980-1d9c-11ea-9b82-75624e70c089.png)

**Comment by enjoyuruf** [comment]
把侧边栏工具关了就没有了。在主题设置里。

**Comment by qwqoo** [comment]
emmm 默认是取消勾选的，新安装会有这个白块，而且勾选->保存 取消勾选-> 保存还是有。。。

**Comment by spirit1431007** [comment]
dev分支已修复

**Comment by qwqoo** [comment]
OK了，dev分支是正常的

**Comment by mashirozx** [comment]
@spirit1431007 dev 应该可以 release 了吧🙃

**Comment by spirit1431007** [comment]
> @spirit1431007 dev 应该可以 release 了吧

#148 merge吗？
