### ISSUE TITLE
回复评论出现时间问题

### ISSUE THREAD

**Issue by Mactor2018** [mashirozx/Sakura#16]
刚刚发出的评论却显示好几个小时之前发出。

**Comment by mashirozx** [comment]
https://2heng.xin/theme-sakura/
见 FAQ 6

**Comment by kot4ri** [comment]
主页显示的文章发布时间在发布后的8小时。

/wp-content/themes/Sakura/inc/theme_plus.php第74行
$newer_date = time() + (8*60*60);

减号改加号了（

到这里仅有“xx小时前”能够显示正常，部分文章发布日期还在正确时间的一天之前，将第66行$comment_date改为true后发现日期也差8小时，按照FAQ6提供的方法，删除_gmt字段后正常。

**Comment by kot4ri** [comment]
FAQ6的补充，theme_plus.php 297行
`    $t .= '<p class="entry-census"><span><a href="'. esc_url(get_author_posts_url(get_the_author_meta('ID'),get_the_author_meta( 'user_nicename' ))) .'"><img src="'. get_avatar_url( get_the_author_meta('ID'), 64 )/*$ava*/ .'"></a></span><span><a href="'. esc_url(get_author_posts_url(get_the_author_meta('ID'),get_the_author_meta( 'user_nicename' ))) .'">'. get_the_author() .'</a></span><span class="bull">·</span>'. poi_time_since(get_post_time('U', false),false,true) .'<span class="bull">·</span>'. get_post_views(get_the_ID()) .' 次阅读</p>';`
(get_post_time('U', false),false,true)第二个括号里给false掉就行了

**Comment by kot4ri** [comment]
> 我自己这边默认状态在凌晨测试会有问题，今天凌晨发的显示7小时前，昨天深夜发的显示5小时前。。。
> 后来试了一下，对于服务器时间本就为+8时区的，把` + (8*60*60)`删掉即可。（并不确定其他人能不能用）
> `/wp-content/themes/Sakura/inc/theme_plus.php第74行`
> `$newer_date = time() + (8*60*60);`

有兴趣的话呢可以在telegram跟我沟通一下 @kot4ri

**Comment by mashirozx** [comment]
已修复，【其他】选项中添加了一个调节项
