### ISSUE TITLE
想询问一下封面接口是否存在异常呢？

### ISSUE THREAD

**Issue by DavinciEvans** [mashirozx/Sakura#170]
**描述问题**
我根据提供的Wiki已经将图片上传到了CDN上，并且已经将图片的json上传到数据库当中。但是封面图依然没有出来。
**bug 重现步骤**
查询网页源码后发现图片地址只能导航到/manifest下，会显示jsdelivr的一个文件菜单。但并不能显示图片。在后台均已设置好图片cdn的地址。
**截图**
![](https://i.loli.net/2019/12/23/5Kw38bgQXBv9dkn.png)
![](https://i.loli.net/2019/12/23/VZiqmWtPeQBfKOC.png)
在访问 http://davincievans.top/wp-json/sakura/v1/image/cover 以后进入的是/manifest的目录界面
![](https://i.loli.net/2019/12/23/KlMFpYJbOaBexfN.png)
查询数据库可以查看到manifest_json已经写入数据库当中
**系统信息**
 - （前端）操作系统: Windows 10
 - 浏览器: chrome
 - PHP 版本 7.2
 - WordPress 版本 5.2.4
 - Sakura 主题版本 3.3.3

**补充信息**
网站地址：http://davincievans.top/

**Comment by spirit1431007** [comment]
确实有问题，我马上修

**Comment by Caibiner** [comment]
小白想问问 这个rest url 应该填啥啊。。

**Comment by DavinciEvans** [comment]
> 小白想问问 这个rest url 应该填啥啊。。

rest url只是一个特定的格式，就根据wiki把前面域名改成自己的就可以用了

**Comment by Caibiner** [comment]
> > 小白想问问 这个rest url 应该填啥啊。。
> 
> rest url只是一个特定的格式，就根据wiki把前面域名改成自己的就可以用了

饿。。我也试过了。。但是跟你一样封面图依旧出不来。。不知道这个Bug修了没

**Comment by DavinciEvans** [comment]
> > > 小白想问问 这个rest url 应该填啥啊。。
> > 
> > 
> > rest url只是一个特定的格式，就根据wiki把前面域名改成自己的就可以用了
> 
> 饿。。我也试过了。。但是跟你一样封面图依旧出不来。。不知道这个Bug修了没

我后面是自己重写了一个api接口作为封面图。就是加载速度比较慢一点就是了

**Comment by Caibiner** [comment]
> > > > 小白想问问 这个rest url 应该填啥啊。。
> > > 
> > > 
> > > rest url只是一个特定的格式，就根据wiki把前面域名改成自己的就可以用了
> > 
> > 
> > 饿。。我也试过了。。但是跟你一样封面图依旧出不来。。不知道这个Bug修了没
> 
> 我后面是自己重写了一个api接口作为封面图。就是加载速度比较慢一点就是了

膜拜大佬。。俺也想写，但是毫无头绪 留下了没有技术的泪水

**Comment by spirit1431007** [comment]
下一release改为后端获取manifest.json，不用Python上传了，可以先试试dev分支

**Comment by Caibiner** [comment]
> > > > 小白想问问 这个rest url 应该填啥啊。。
> > > 
> > > 
> > > rest url只是一个特定的格式，就根据wiki把前面域名改成自己的就可以用了
> > 
> > 
> > 饿。。我也试过了。。但是跟你一样封面图依旧出不来。。不知道这个Bug修了没
> 
> 我后面是自己重写了一个api接口作为封面图。就是加载速度比较慢一点就是了

哇 大佬也是桂林的么。。 = =缘分呐

**Comment by mashirozx** [comment]
> 下一release改为后端获取manifest.json，不用Python上传了，可以先试试dev分支

催更 (ಥ _ ಥ)

**Comment by DavinciEvans** [comment]
> > > > > 小白想问问 这个rest url 应该填啥啊。。
> > > > 
> > > > 
> > > > rest url只是一个特定的格式，就根据wiki把前面域名改成自己的就可以用了
> > > 
> > > 
> > > 饿。。我也试过了。。但是跟你一样封面图依旧出不来。。不知道这个Bug修了没
> > 
> > 
> > 我后面是自己重写了一个api接口作为封面图。就是加载速度比较慢一点就是了
> 
> 哇 大佬也是桂林的么。。 = =缘分呐

hhhh我不是dalao啦。。。我现在主要在上海读书orz，之后也可以加个好友相互交流一下喔：）

**Comment by spirit1431007** [comment]
最新版已修复，同时，manifest.json改为后端获取。https://github.com/mashirozx/Sakura/wiki/options

**Comment by DavinciEvans** [comment]
> 最新版已修复，同时，manifest.json改为后端获取。https://github.com/mashirozx/Sakura/wiki/options

似乎最新版还是没有解决呢，还是说我的操作有问题orz

**Comment by Caibiner** [comment]
最新版好像还是不行的样子，，manifest.py运行报错。。请问大佬还有什么比较简单的方法，比如手动修改封面图和随机封面图吗。。小白一枚。。cdn是用阿里云里的。。😖------------------ 原始邮件 ------------------
发件人: "Spirit"<notifications@github.com>
发送时间: 2019年12月26日(星期四) 晚上9:04
收件人: "mashirozx/Sakura"<Sakura@noreply.github.com>;
抄送: "Caibiner"<aomiao9311z@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [mashirozx/Sakura] 想询问一下封面接口是否存在异常呢？ (#170)



最新版已修复，同时，manifest.json改为后端获取。https://github.com/mashirozx/Sakura/wiki/options
 
&mdash;

**Comment by Caibiner** [comment]
最新版好像还是不行的样子，，manifest.py运行报错。。请问大佬还有什么比较简单的方法，比如手动修改封面图和随机封面图吗。。大体的流程和方法也行。。小白一枚。。cdn是用阿里云里的。。

**Comment by spirit1431007** [comment]
> 似乎最新版还是没有解决呢，还是说我的操作有问题orz

我这边测试是没问题的，填写 `https://cdn.jsdelivr.net/gh/DavinciEvans/Imgs-bed@master` 并保存，然后访问 `https://example.com/wp-json/sakura/v1/database/update` 更新数据库，之后访问 `https://example.com/wp-json/sakura/v1/image/cover` 会返回封面图片

**Comment by spirit1431007** [comment]
> 最新版好像还是不行的样子，，manifest.py运行报错。。请问大佬还有什么比较简单的方法，比如手动修改封面图和随机封面图吗。。大体的流程和方法也行。。小白一枚。。cdn是用阿里云里的。。

报错的信息是什么呢，是否正确安装相关依赖

**Comment by DavinciEvans** [comment]
> > 似乎最新版还是没有解决呢，还是说我的操作有问题orz
> 
> 我这边测试是没问题的，填写 `https://cdn.jsdelivr.net/gh/DavinciEvans/Imgs-bed@master` 并保存，然后访问 `https://example.com/wp-json/sakura/v1/database/update` 更新数据库，之后访问 `https://example.com/wp-json/sakura/v1/image/cover` 会返回封面图片

![GIF.gif](https://i.loli.net/2019/12/27/Aa8kpJXSU2BsLyZ.gif)
这里记录了我的操作，图床就在我当前的github里。dalao能看一下是我的操作失误嘛，不知道是什么问题呢？＞﹏＜
所有操作均在无痕下进行。

**Comment by DavinciEvans** [comment]
> > 似乎最新版还是没有解决呢，还是说我的操作有问题orz
> 
> 我这边测试是没问题的，填写 `https://cdn.jsdelivr.net/gh/DavinciEvans/Imgs-bed@master` 并保存，然后访问 `https://example.com/wp-json/sakura/v1/database/update` 更新数据库，之后访问 `https://example.com/wp-json/sakura/v1/image/cover` 会返回封面图片

![QQ截图20191227110748.png](https://i.loli.net/2019/12/27/UK6v7d4hbZSecAt.png)
emmmmmm是否是数据库那边出现问题呢？在我将Cover manifest设置成一个自己的应用之后，访问`https://example.com/wp-json/sakura/v1/database/update`之后只是单纯地在我的应用地址后面添加了/manifest。
另外还希望在未来的版本中能像之前一样能够使用自建的封面api设置。

**Comment by spirit1431007** [comment]
操作是没问题的，可能是数据库存取错误了-_- ，你检查看看数据库存进东西没，`manifest_json`的值是否与manifest.json一致

**Comment by DavinciEvans** [comment]
> 操作是没问题的，可能是数据库存取错误了-_- ，你检查看看数据库存进东西没，`manifest_json`的值是否与manifest.json一致

的确是这样，但在我将`manifest_json`的值修改成与manifest.json的值一致之后依然没有成功orz

**Comment by spirit1431007** [comment]
> 的确是这样，但在我将`manifest_json`的值修改成与manifest.json的值一致之后依然没有成功orz

我需要详细了解情况，可以加入主题交流群（860262481）吗，我会细细排查问题的～

**Comment by Caibiner** [comment]
> > 最新版好像还是不行的样子，，manifest.py运行报错。。请问大佬还有什么比较简单的方法，比如手动修改封面图和随机封面图吗。。大体的流程和方法也行。。小白一枚。。cdn是用阿里云里的。。
> 
> 报错的信息是什么呢，是否正确安装相关依赖

额。。我改了很多东西更新感觉挺麻烦的。。所以想问问有什么办法手动修改下这个封面随机图呢。。

**Comment by spirit1431007** [comment]
最新版已修复：https://github.com/mashirozx/Sakura/releases/tag/v3.3.6
