### ISSUE TITLE
“第一屏”的翻译不妥

### ISSUE THREAD

**Issue by mashirozx** [mashirozx/Sakura#177]
![image](https://user-images.githubusercontent.com/16148054/71496854-6863e400-2890-11ea-92cb-44cc654a018f.png)

可以用 "Homepage" 或者 "Index". 手头没有poteditor，方便的话帮忙改一下 @spirit1431007 

顺便改了一下文件路径，现在应该可以不要求改文件夹名为 Sakura 了.

以后更新版本改 style.css 里面的就可以了.

**Comment by spirit1431007** [comment]
emmm，看看这个：https://en.wikipedia.org/wiki/Above_the_fold

**Comment by mashirozx** [comment]
专业~我还以为是机器翻译的
