### ISSUE TITLE
1头像加载较慢2自定义一言

### ISSUE THREAD

**Issue by samondlee** [mashirozx/Sakura#18]
1、gravatar.shino.cc可能人使用比较多，有些地方再状态栏加载老半天，可否考虑在下一版 改为本地头像库或api

2、能加入自定义看板娘在后台 选择最好了，https://imjad.cn/archives/lab/add-dynamic-poster-girl-with-live2d-to-your-blog-03 推荐这个血小板

3、现在 博主介绍里 只有一句话，在下一版中如果加入 可以自己选择的 一言api最好了，比如 

function getHitokoto() {
$.ajax({
        url: "http://2sr.likeqi.cn/api.php?encode=jsc&cat=a&charset=utf-8&length=50",
        dataType: "jsonp",
        async: true,
      jsonp: "callback",
      jsonpCallback: "hitokoto",
        success: function(result) {
  $('#hitokoto').html("<p>" + result.hitokoto + "</p>")
        },
        error: function() {
  $('#hitokoto').html("<p>读取数据失败了的说……_(:з」∠)_</p>")
        }
         });
 }
getHitokoto()

**Comment by hifocus** [comment]
主题设定里面应该会有那个什么自定义 Gravatar 头像地址，你可以切换成 `gravatar.loli.net` 国内阿里云，海外 Cloudflare，速度应该是综合来说最好的。

**Comment by hifocus** [comment]
`gravatar.shino.cc` was served with Cloudflare. To be honest I wouldn't suggest you to use it in productive way because of its terrible experience in China. @mashirozx

**Comment by mashirozx** [comment]
Substitute it with whatever you like here: https://github.com/mashirozx/Sakura/blob/master/functions.php#L533
