### ISSUE TITLE
又想重写评论模块了:(

### ISSUE THREAD

**Issue by mashirozx** [mashirozx/Sakura#181]
react的state真的方便，可以省掉一大堆代码:neutral_face:

**Comment by LittleControl** [comment]
写,永远支持大佬,哈哈哈

**Comment by mashirozx** [comment]
> 写,永远支持大佬,哈哈哈

谢谢大佬支持
![image](https://user-images.githubusercontent.com/16148054/71557914-ffdf5780-2a87-11ea-8c5c-b1f9171a7fa1.png)

**Comment by LittleControl** [comment]
O(∩_∩)O哈哈~
可惜的是我不是大佬,
连菜鸡都算不上┭┮﹏┭┮

**Comment by mashirozx** [comment]
菜鸡互啄？
![image](https://user-images.githubusercontent.com/16148054/71557977-ea1e6200-2a88-11ea-814b-43b64d518d6b.png)

**Comment by LittleControl** [comment]
> 菜鸡互啄？
> ![image](https://user-images.githubusercontent.com/16148054/71557977-ea1e6200-2a88-11ea-814b-43b64d518d6b.png)

那你就是一个鸡妈妈,我顶多还是一个鸡蛋,我还没出生,你都已经回飞了
(*^▽^*)

**Comment by enjoyuruf** [comment]
真正的菜鸡看着大佬互相谦让。
我才是真正的害怕
![image](https://user-images.githubusercontent.com/39794567/71558014-70d33f00-2a89-11ea-8118-47edbb869516.png)
