### ISSUE TITLE
sidebar 相关

### ISSUE THREAD

**Issue by mashirozx** [mashirozx/Sakura#183]
![image](https://user-images.githubusercontent.com/16148054/71867886-f53b5700-3146-11ea-95dc-bdd03f8535a1.png)

cc: @spirit1431007

**Comment by spirit1431007** [comment]
了解👌，加个延时就好了

**Comment by spirit1431007** [comment]
最新版已修复：https://github.com/mashirozx/Sakura/releases/tag/v3.3.6
