### ISSUE TITLE
从github下了最新版覆盖了之后不显示首页cover

### ISSUE THREAD

**Issue by samondlee** [mashirozx/Sakura#184]
**描述问题**
1.原来首页cover一直是显示的，这次直接覆盖了，我看目录里也没有cover目录，然后载入首页的时候原来的cover都是空白。然后 主题设置里面也没找到cover设置地址。。。== 
2.文章封面使用的随机封面，上次的黑底封面修复了 一直很好用，这次再用的时候第一个文章可以有封面，第二个文章显示不出来封面 类似 没下载完的那种图标，一直在载入状态。

**bug 重现步骤**

**截图（如有）**

**系统信息**
 - （前端）操作系统: [e.g. Windows 10, Android 9.0]
 - 浏览器: [e.g. chrome, safari]
Edge Dev
 - PHP 版本
 - WordPress 版本
最新
 - Sakura 主题版本
最新

**补充信息**
http://blog.uss.moe:9988/

**Comment by samondlee** [comment]
emmm,研究了一下manifest会了= =，之前没有用过cdn.jsdeliver.net一时间反应不过来。。

另外文章feature有概率显示相同图片，不知道可不可以优化一下，在有充足图片的情况下尽量不要让随即图 同一页的 文章1 文章2 文章3获取的随即图重合，（当然如果图片少的话也可以重）

**Comment by samondlee** [comment]
还有 就是这次采用了manifest 之后 ，在文章页 抬头的 文章标题 cover 图片好像不见了= =不知道怎么设置= =

标题的cover图 可否也采用随机图？

**Comment by spirit1431007** [comment]
新版会有自定义api和调用随机调用本地图片的选项。
你说的标题cover图是文章页面的头图吗，那需要自己在WordPress设置特色图片才会显示。

**Comment by samondlee** [comment]
> 新版会有自定义api和调用随机调用本地图片的选项。
> 你说的标题cover图是文章页面的头图吗，那需要自己在WordPress设置特色图片才会显示。

= =1.对的，就是把主题有cdn的随机图API给外部网站调用= =
2.emmm，对的 就是文章页面的 头图，如果能加一个开关 也和首页特色图 一样都是随机的就好了，有时候就像吐槽一句话也要配图才好看点儿 感觉有点儿麻烦= =

**Comment by spirit1431007** [comment]
最新版已添加自定义封面接口选项：https://github.com/mashirozx/Sakura/releases/tag/v3.3.6

**Comment by samondlee** [comment]
> 最新版已添加自定义封面接口选项：https://github.com/mashirozx/Sakura/releases/tag/v3.3.6

QAQ, 博客的 随机图能不能有一个引出 对外服务的 index.php 页

因为有cdn感觉速度很快 ，想给其他站也用，可否直接引用博客主题的= =
