### ISSUE TITLE
请问能否将缩略图和封面分开设定？

### ISSUE THREAD

**Issue by GavinZhengOI** [mashirozx/Sakura#187]
请问能不能手动指定封面图片而文章的缩略图使用随机图片库？

**Comment by enjoyuruf** [comment]
你应该是指，文章的封面图和首页显示的文章的缩略图显示不同的图片吧。

**Comment by spirit1431007** [comment]
文章特色图片是需要自己设置的，写文章不配图的情况应该很少吧，文章随机图只是作为备选😁

**Comment by GavinZhengOI** [comment]
是的QAQ





------------------ 原始邮件 ------------------
发件人: enjoyuruf <notifications@github.com&gt;
发送时间: 2020年2月13日 20:07
收件人: mashirozx/Sakura <Sakura@noreply.github.com&gt;
抄送: GavinZhengOI <1798731896@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[mashirozx/Sakura] 请问能否将缩略图和封面分开设定？ (#187)




你应该是指，文章的封面图和首页显示的文章的缩略图显示不同的图片吧。

**Comment by GavinZhengOI** [comment]
我一般写博客只有公式没有图23333333


其实现在想想 手动指定张文章图片也就几秒钟的事情。QAQ


谢谢咯～





------------------ 原始邮件 ------------------
发件人: Spirit <notifications@github.com&gt;
发送时间: 2020年2月13日 20:29
收件人: mashirozx/Sakura <Sakura@noreply.github.com&gt;
抄送: GavinZhengOI <1798731896@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[mashirozx/Sakura] 请问能否将缩略图和封面分开设定？ (#187)




文章特色图片是需要自己设置的，写文章不配图的情况应该很少吧，文章随机图只是作为备选😁
