### ISSUE TITLE
PJAK局部刷新启用后点开文章不显示图片，要手动再刷新一次才有图片

### ISSUE THREAD

**Issue by gitxxp** [mashirozx/Sakura#188]
**描述问题**
PJAK局部刷新启用后点开文章不显示图片，要手动再刷新一次才有图片
**bug 重现步骤**
PJAK局部刷新启用后点开文章不显示图片，要手动再刷新一次才有图片

**系统信息**
 - （前端）操作系统: [Windows 10]
 - 浏览器: [chrome]
 - PHP 版本7.3
 - WordPress 版本5.32
 - Sakura 主题版本.3.3

**Comment by spirit1431007** [comment]
信息不足，请参照issue模板提供

**Comment by gitxxp** [comment]
> 信息不足，请参照issue模板提供

已添加

**Comment by spirit1431007** [comment]
更新到 [v3.3.6](https://github.com/mashirozx/Sakura/releases/tag/v3.3.6) 是否还有此问题

**Comment by gitxxp** [comment]
> 更新到 [v3.3.6](https://github.com/mashirozx/Sakura/releases/tag/v3.3.6) 是否还有此问题
有

**Comment by spirit1431007** [comment]
发一下复现此bug的网站地址

**Comment by gitxxp** [comment]
> 发一下复现此bug的网站地址

https://xxp.wtf/

**Comment by spirit1431007** [comment]
> https://xxp.wtf/

应该是jetpack插件的功能与主题自带的lazyload冲突，请在插件中关闭图片懒加载的相关功能再试试

**Comment by gitxxp** [comment]
> > https://xxp.wtf/
> 
> 应该是jetpack插件的功能与主题自带的lazyload冲突，请在插件中关闭图片懒加载的相关功能再试试
已关闭懒加载，好像还是一样

**Comment by gitxxp** [comment]
> > > https://xxp.wtf/
> > 
> > 
> > 应该是jetpack插件的功能与主题自带的lazyload冲突，请在插件中关闭图片懒加载的相关功能再试试
> > 已关闭懒加载，好像还是一样



> > https://xxp.wtf/
> 
> 应该是jetpack插件的功能与主题自带的lazyload冲突，请在插件中关闭图片懒加载的相关功能再试试

我把jetpack关了，果然好了，但是不关jetpack只关懒加载不行，有其他解决办法吗

**Comment by gitxxp** [comment]
问题解决了，确实是与jetpack的延迟加载冲突了，把jetpack的延迟加载关闭就正常了，感谢
