### ISSUE TITLE
Chromium版Edge UA检测需要更新，移除dev

### ISSUE THREAD

**Issue by mashirozx** [mashirozx/Sakura#189]
**描述问题**

**bug 重现步骤**

**截图（如有）**

**系统信息**
 - （前端）操作系统: [e.g. Windows 10, Android 9.0]
 - 浏览器: [e.g. chrome, safari]
 - PHP 版本
 - WordPress 版本
 - Sakura 主题版本

**补充信息**

**Comment by spirit1431007** [comment]
done
