### ISSUE TITLE
question:大佬还是不会修改description为一言QAQ

### ISSUE THREAD

**Issue by samondlee** [mashirozx/Sakura#19]
question:大佬还是不会修改description为一言QAQ

比如说调用这个JS QAQ 

http://n1.likeqi.cn:8888/public/js/n1hitokoto.js

**Comment by mashirozx** [comment]
参考 https://2heng.xin/2017/08/12/hitokoto/
根据情况修改选择器`document.querySelector()`中的元素class或者id
以Sakura为例，你还需要给description的<p>标签加上一个class或者id

**Comment by SoraKasvgano** [comment]
> 参考 https://2heng.xin/2017/08/12/hitokoto/
> 
> 根据情况修改选择器`document.querySelector()`中的元素`class`或者`id`
> 以Sakura为例，你还需要给description的`<p>`标签加上一个`class`或者`id`。另外还要注意添加相应的pjax回调函数。
> 
> ![image](https://user-images.githubusercontent.com/16148054/48766397-5ad44600-ecef-11e8-80de-636ba246703f.png)
> 
> 我的建议是不要在description处调用API，除非你能控制句子长度，否则样式很难控制；为什么不加在公告那里呢？

QAQ谢谢大佬 耐心的回复= =！！！

又发现了新的问题！

[http://naxxxxx83/2018/11/13/hello-world/](url)

回复框在显示错位（chrome最新版，您的博客没有错位，会不会是因为端口号问题）

![default](https://user-images.githubusercontent.com/8521327/48855614-598a4280-edef-11e8-8ce7-fe53f235cb77.JPG)



还有我可以收到系统发出的 让我审核评论的邮件

但是无法向您的博客那样 给 访客的评论  回复后 访客收到邮件通知QAQ

functions没改过 都是默认的，后台插件也安了Easy WP SMTP

**Comment by SoraKasvgano** [comment]
> > 参考 https://2heng.xin/2017/08/12/hitokoto/
> > 根据情况修改选择器`document.querySelector()`中的元素`class`或者`id`
> > 以Sakura为例，你还需要给description的`<p>`标签加上一个`class`或者`id`。另外还要注意添加相应的pjax回调函数。
> > ![image](https://user-images.githubusercontent.com/16148054/48766397-5ad44600-ecef-11e8-80de-636ba246703f.png)
> > 我的建议是不要在description处调用API，除非你能控制句子长度，否则样式很难控制；为什么不加在公告那里呢？
> 
> QAQ谢谢大佬 耐心的回复= =！！！
> 
> 又发现了新的问题！
> 
> [http://xxxn:83/2018/11/22/hello-world/](url)
> 
> 回复框在显示错位（chrome最新版，您的博客没有错位，会不会是因为端口号问题）
> 
> ![default](https://user-images.githubusercontent.com/8521327/48855614-598a4280-edef-11e8-8ce7-fe53f235cb77.JPG)
> 
> 还有我可以收到系统发出的 让我审核评论的邮件
> 
> 但是无法向您的博客那样 给 访客的评论 回复后 访客收到邮件通知QAQ
> 
> functions没改过 都是默认的，后台插件也安了Easy WP SMTP

原因好像如下

```
wp-config.php，在define(‘WP_DEBUG’, false);后面添加下面内容：

define('WP_SITEURL', 'http://' . $_SERVER['HTTP_HOST']);
define('WP_HOME', 'http://' . $_SERVER['HTTP_HOST']);
```

不知道是不是这个原因。。。我设置了没有绑定域名。。。。

关于回复无法收发信件的问题，好像是由于我使用了WP-Optimize 把相关信息删除了，但是不知道删除了哪一块- -

**Comment by samondlee** [comment]
> 参考 https://2heng.xin/2017/08/12/hitokoto/
> 
> 根据情况修改选择器`document.querySelector()`中的元素`class`或者`id`
> 以Sakura为例，你还需要给description的`<p>`标签加上一个`class`或者`id`。另外还要注意添加相应的pjax回调函数。
> 
> ![image](https://user-images.githubusercontent.com/16148054/48766397-5ad44600-ecef-11e8-80de-636ba246703f.png)
> 
> 我的建议是不要在description处调用API，除非你能控制句子长度，否则样式很难控制；为什么不加在公告那里呢？

最新情况，邮件可以发送了 是因为wp-optimize不知道删了什么

但是回复栏仍然错位，怀疑真的是因为端口问题

**Comment by mashirozx** [comment]
> > 参考 https://2heng.xin/2017/08/12/hitokoto/
> > 根据情况修改选择器`document.querySelector()`中的元素`class`或者`id`
> > 以Sakura为例，你还需要给description的`<p>`标签加上一个`class`或者`id`。另外还要注意添加相应的pjax回调函数。
> > ![image](https://user-images.githubusercontent.com/16148054/48766397-5ad44600-ecef-11e8-80de-636ba246703f.png)
> > 我的建议是不要在description处调用API，除非你能控制句子长度，否则样式很难控制；为什么不加在公告那里呢？
> 
> QAQ谢谢大佬 耐心的回复= =！！！
> 
> 又发现了新的问题！
> 
> [http://nas.likeqi.cn:83/2018/11/13/hello-world/](url)
> 
> 回复框在显示错位（chrome最新版，您的博客没有错位，会不会是因为端口号问题）
> 
> ![default](https://user-images.githubusercontent.com/8521327/48855614-598a4280-edef-11e8-8ce7-fe53f235cb77.JPG)
> 
> 还有我可以收到系统发出的 让我审核评论的邮件
> 
> 但是无法向您的博客那样 给 访客的评论 回复后 访客收到邮件通知QAQ
> 
> functions没改过 都是默认的，后台插件也安了Easy WP SMTP

我这里正常，可能是你浏览器哪个插件的问题
![image](https://user-images.githubusercontent.com/16148054/48920081-b3fbcf80-eed1-11e8-81b5-a007350e0033.png)

邮件的话试试安装推荐插件里的那个STMP插件

**Comment by SoraKasvgano** [comment]
> > > 参考 https://2heng.xin/2017/08/12/hitokoto/
> > > 根据情况修改选择器`document.querySelector()`中的元素`class`或者`id`
> > > 以Sakura为例，你还需要给description的`<p>`标签加上一个`class`或者`id`。另外还要注意添加相应的pjax回调函数。
> > > ![image](https://user-images.githubusercontent.com/16148054/48766397-5ad44600-ecef-11e8-80de-636ba246703f.png)
> > > 我的建议是不要在description处调用API，除非你能控制句子长度，否则样式很难控制；为什么不加在公告那里呢？
> > 
> > 
> > QAQ谢谢大佬 耐心的回复= =！！！
> > 又发现了新的问题！
> > [http://nxxxxn:83/2018/11/13/hello-world/](url)
> > 回复框在显示错位（chrome最新版，您的博客没有错位，会不会是因为端口号问题）
> > ![default](https://user-images.githubusercontent.com/8521327/48855614-598a4280-edef-11e8-8ce7-fe53f235cb77.JPG)
> > 还有我可以收到系统发出的 让我审核评论的邮件
> > 但是无法向您的博客那样 给 访客的评论 回复后 访客收到邮件通知QAQ
> > functions没改过 都是默认的，后台插件也安了Easy WP SMTP
> 
> 我这里正常，可能是你浏览器哪个插件的问题
> ![image](https://user-images.githubusercontent.com/16148054/48920081-b3fbcf80-eed1-11e8-81b5-a007350e0033.png)
> 
> 邮件的话试试安装推荐插件里的那个STMP插件

没有插件，已经重置辣，还是不行呜呜呜

chrome版本号70.0.3538.102

**Comment by mashirozx** [comment]
同Chrome版本号。。主题设置里有个选项可以调整宽度，试试看吧
