### ISSUE TITLE
无法调用外部随机图api

### ISSUE THREAD

**Issue by guhailong18** [mashirozx/Sakura#190]
**描述问题**
无法调用外部随机图api
**bug 重现步骤**
网址：https://www.dream18.xyz/   封面空白或是一张不变的本地图片
API地址：http://www.dmoe.cc/random.php

**系统信息**
 - （前端）操作系统: [e.g. cenos
 - 浏览器: [e.g. chrome, safari] chrome
 - PHP 版本   72
 - WordPress 版本 最新
 - Sakura 主题版本  3.3.6

**补充信息**
本地的调用实在太慢，现在不知道是不是CDN的缓存还是怎样，就只出现了一张本地图（服务器上的）
F12发现如下问题
Mixed Content: The page at 'https://www.dream18.xyz/' was loaded over HTTPS, but requested an insecure image 'http://www.dream18.xyz/wp-content/themes/Sakura/images//temp.png'. This content should also be served over HTTPS.
不知如何修改为https，求大佬解答

**Comment by mashirozx** [comment]
网页与接口的协议不同，在https的页面上不能使用http的资源

**Comment by guhailong18** [comment]
请问这个请求服务器的图片能把它改成https的吗？
而且这个是请求服务器上的，应该与调用外部API没有什么关系才对，那是因为什么才无法调用的？求大佬解答！

**Comment by guhailong18** [comment]
> 网页与接口的协议不同，在https的页面上不能使用http的资源
请问这个请求服务器的图片能把它改成https的吗？
而且这个是请求服务器上的，应该与调用外部API没有什么关系才对，那是因为什么才无法调用的？求大佬解答！

**Comment by enjoyuruf** [comment]
![image](https://user-images.githubusercontent.com/39794567/75599987-08362c00-5ae5-11ea-895d-fafb0cc0568b.png)
打开这个的话，应该可以加载http 的内容
在Chrome的网站设置里面。

**Comment by mashirozx** [comment]
图片是在前端加载的，浏览器安全策略不允许

**Comment by guhailong18** [comment]
那个API的调用也是这个原因吗？

**Comment by mashirozx** [comment]
你换这个接口试试，保证没问题 https://api.2heng.xin/cover

**Comment by enjoyuruf** [comment]
![image](https://user-images.githubusercontent.com/39794567/75600213-ae833100-5ae7-11ea-8640-1dc5642d9734.png)
我这样设置后，没有问题，能正常显示，就是网页的小锁没有了

**Comment by guhailong18** [comment]
使用大佬的API成功解决了，我可以一直使用这个API吗？

**Comment by guhailong18** [comment]
那个图片加载不出来是因为腾讯云我使用强制https，现在改回来了，感谢各位大佬的帮助！
