### ISSUE TITLE
评论回复的提醒邮件未发送

### ISSUE THREAD

**Issue by Hoshino-Hikari** [mashirozx/Sakura#191]
php7.2, LAMP
安装了Easy WP SMTP，测试邮件发送成功，且评论审核的邮件可以自动发送，但是那个Sakura主题自带的那个评论回复的邮件却没有效果，收不到。
且“管理中心>外观>Sakura主题设置>其他>邮件回复通知管理员”以及下面两个复选框均已勾选。

**Comment by mashirozx** [comment]
确认一下发件邮箱里面有没有发件记录？

**Comment by mashirozx** [comment]
feel free to reopen again :)

**Comment by Hoshino-Hikari** [comment]
后来我是先安装了那个叫“Easy WP SMTP”的插件再装的主题，莫名其妙好了
