### ISSUE TITLE
child主题内文件不起作用

### ISSUE THREAD

**Issue by feilongproject** [mashirozx/Sakura#194]
我在child主题内的inc/swicher.php里修改的`mashiro_option.cover_api`参数直接改成了直链，但在预览时还是用的原来dev分支里的[http://website.com/index.php?rest_route=/sakura/v1/image/cover?1)](http://website.com/index.php?rest_route=/sakura/v1/image/cover?1)，但其他文件（如header.php）里更改的样式还能用，请问是什么问题？  
 
------

另外一个小问题，当我在封面图片库用外链API时，在第一屏点击左右图片切换时，使用的链接却是[http://website.com/index.php?rest_route=/sakura/v1/image/cover?1](http://website.com/index.php?rest_route=/sakura/v1/image/cover?1)，而且在新窗口打开后提示`{"code":"rest_no_route","message":"\u672a\u627e\u5230\u5339\u914dURL\u548c\u8bf7\u6c42\u65b9\u5f0f\u7684\u8def\u7531","data":{"status":404}}`，但去掉结尾的`?1`后就可以返回随机图了，请问这是什么问题？

**Comment by spirit1431007** [comment]
配置伪静态，且设置固定链接为非朴素

**Comment by feilongproject** [comment]
> 配置伪静态，且设置固定链接为非朴素

多谢！现在已经解决了
