### ISSUE TITLE
本地manifest发生403 Forbidden

### ISSUE THREAD

**Issue by SinxLinonZ** [mashirozx/Sakura#197]
使用内置原图随机时
https://my-domain.com/wp-json/sakura/v1/image/cover
可正常返回
https://my-domain.com/wp-content/themes/Sakura/manifest/gallary/
以获取封面原图

当使用webp优化随机图且使用本地库时（即封面图片库url留空），返回
https://my-domain.com/wp-content/themes/Sakura/manifest/
此时发生403导致无法显示第一屏背景图

检查过应该不是权限的问题
求教

**Comment by spirit1431007** [comment]
使用webp优化随机图需要先先访问 https://my-domain.com/wp-json/sakura/v1/database/update 更新manifest

**Comment by SinxLinonZ** [comment]
封面图片库url留空之后我更新了manifest，返回`"manifest.json has been stored into database."`
但是依然是403

**Comment by SinxLinonZ** [comment]
数据库内容为
`MariaDB [wordpress]> select * from wp_sakura\G;
*************************** 1. row ***************************
  mate_key: manifest_json
mate_value: {"19313b0d62b27c8ba022f60fbfedd5ee": {"source": "beyond_by_auroralion-dan5njb.jpg", "jpeg": ["jpeg/19313b0d62b27c8ba022f60fbfedd5ee.jpeg", "jpeg/19313b0d62b27c8ba022f60fbfedd5ee.th.jpeg"], "webp": ["webp/19313b0d62b27c8ba022f60fbfedd5ee.webp", "webp/19313b0d62b27c8ba022f60fbfedd5ee.th.webp"]}, "e9f33c2c502ab43804964ce7edd431f9": {"source": "\udce6\udcb5\udcb7\udce3\udc81\udcae\udce7\udca9\udcba(56993195)_by_\udce5\udca4\udc8fT.jpg", "jpeg": ["jpeg/e9f33c2c502ab43804964ce7edd431f9.jpeg", "jpeg/e9f33c2c502ab43804964ce7edd431f9.th.jpeg"], "webp": ["webp/e9f33c2c502ab43804964ce7edd431f9.webp", "webp/e9f33c2c502ab43804964ce7edd431f9.th.webp"]}, "783bf161f47b32882f0e962fd4064de7": {"source": "pixar_up_movie_balloons_desktop_1920x1080_hd-wallpaper-507967.jpg", "jpeg": ["jpeg/783bf161f47b32882f0e962fd4064de7.jpeg", "jpeg/783bf161f47b32882f0e962fd4064de7.th.jpeg"], "webp": ["webp/783bf161f47b32882f0e962fd4064de7.webp", "webp/783bf161f47b32882f0e962fd4064de7.th.webp"]}, "4eb5c9be3dfe4adf66cb0bb12031ad3a": {"source": "78952908_p0.png", "jpeg": ["jpeg/4eb5c9be3dfe4adf66cb0bb12031ad3a.jpeg", "jpeg/4eb5c9be3dfe4adf66cb0bb12031ad3a.th.jpeg"], "webp": ["webp/4eb5c9be3dfe4adf66cb0bb12031ad3a.webp", "webp/4eb5c9be3dfe4adf66cb0bb12031ad3a.th.webp"]}}
*************************** 2. row ***************************
  mate_key: privkey
mate_value: AbEwwT!k
*************************** 3. row ***************************
  mate_key: json_time
mate_value: 2020-03-19 01:35:33
3 rows in set (0.00 sec)`

和本地的文件是相符的

**Comment by spirit1431007** [comment]
在`图片库url`处填写 https://my-domain.com/wp-content/themes/Sakura 后访问封面图api是否正常？

**Comment by SinxLinonZ** [comment]
`图片库url` -> https://my-domain.com/wp-content/themes/Sakura
无效，返回https://my-domain.com/wp-content/themes/Sakura/manifest/   403 Forbidden

`图片库url` -> https://my-domain.com/wp-content/themes/Sakura -> `更新 manifest`
无效，返回https://my-domain.com/wp-content/themes/Sakura/manifest/   403 Forbidden


系统环境：
Nginx 1.14
PHP 7.2
MariaDB 10
Wordpress 5.3.2

Nginx配置：
upstream php {
        server unix:/var/run/php/php7.2-fpm.sock;
}

server {
        server_name my-domain.com;
        root /path/to/wordpress;
        index index.php;

        location = /favicon.ico {
                log_not_found off;
                access_log off;
        }

        location = /robots.txt {
                allow all;
                log_not_found off;
                access_log off;
        }

        location / {
                try_files $uri $uri/ /index.php?$args;
        }

        location ~ \.php$ {
                include fastcgi_params;
                fastcgi_intercept_errors on;
                fastcgi_pass php;
                #The following parameter can be also included in fastcgi_params file
                fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }

        location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
                expires max;
                log_not_found off;
        }


    listen 443 ssl; # managed by Certbot
    ssl_certificate /path/to/fullchain.pem; 
    ssl_certificate_key /path/to/privkey.pem; 
    include /path/to/options-ssl-nginx.conf; 
    ssl_dhparam /path/to/ssl-dhparams.pem; 

}
redirect省略

wordpress目录均为www-data:www-data所属，manifest为755属性

**Comment by spirit1431007** [comment]
经测试是manifest的问题，你将 https://cdn.jsdelivr.net/gh/mashirozx/sakura@3.3.3 `填入图片库url`再更新看看

**Comment by SinxLinonZ** [comment]
啊不好意思忘记说这个了
用这个cdn的时候是可以的，问题出在本地

**Comment by spirit1431007** [comment]
发现后台文件名处理错误，`e9f33c2c502ab43804964ce7edd431f9`这张图的文件名是什么

**Comment by SinxLinonZ** [comment]
gallary中的原图文件名是`海の空(56993195)_by_夏T.jpg`
是一张默认存在的图

**Comment by spirit1431007** [comment]
请提供一下python的运行环境（操作系统，py版本)

**Comment by SinxLinonZ** [comment]
系统：LXC中的Ubuntu18.04
Python：3.6.9
已安装pip3,PIL

其中有一张图是我后来所加的，文件名为`78952908_p0.png`
对应`4eb5c9be3dfe4adf66cb0bb12031ad3a`

**Comment by spirit1431007** [comment]
emmm, python更新到 [3.7](https://docs.python.org/3/whatsnew/3.7.html) 再看看？

**Comment by SinxLinonZ** [comment]
！！！哇可以了
这个和python版本有关系吗原来
超级感谢！！！！！
