### ISSUE TITLE
The link you followed has expired.

### ISSUE THREAD

**Issue by fufenghua** [mashirozx/Sakura#2]
请问一下，为什么安装的时候，上传100%就跳到这个页面，提示：The link you followed has expired.
然后就安装失败了。

**Comment by mashirozx** [comment]
试试 git clone 或者 FTP 上传

**Comment by hifocus** [comment]
I think you might having problems on managing your server. You might want to think about find a web hosting service which support cPanel. cPanel is a statble admin dashboard and you can just make everyting very easy.

**Comment by hifocus** [comment]
Git glone might not fit for this situation, obviously he is using some kind of web hosting services but not a individual VPS. FTP is fine, but usually lack of speed and good client. So I will suggest you change to a web hosting provider which support cPanel.

**Comment by fufenghua** [comment]
我后来仔细看了一下，我通过控制面板上传安装了另一个主题，并启用成功了，但是我去themes文件夹，却没有看到上传成功的那个主题的文件夹。所以我之前把这个包直接放到themes下，所以才没有用。估计他上传之后不是在themes这个文件夹下了，我也不知道它到底在哪儿了。主要是我是用docker启动的，没有自己部署

**Comment by mashirozx** [comment]
显然这并不是主题的问题。可以参考 https://share.2heng.xin/index.php?share/file&user=1&sid=9FVfpIx3

**Comment by fufenghua** [comment]
emmm  应该不算是主题的锅，刚才我找到原因了，默认安装的php 文件上传大小是2M ，这个包是9M，导致上传过程中报The link you followed has expired.  然后我把php.ini的配置改大了，改到20M，再次安装，就没事了
