### ISSUE TITLE
主题移植申请

### ISSUE THREAD

**Issue by adlered** [mashirozx/Sakura#200]
大佬你好！我是开源项目 [Bolo 菠萝博客](https://github.com/adlered/bolo-solo) 的维护者，觉得 [Sakura](https://github.com/mashirozx/Sakura) 这款主题是少有的几款十分精致好看的主题，希望作者可以授权我们移植到我们的博客系统当中，感谢！:smile:

**Comment by mashirozx** [comment]
你好，OK的😁

**Comment by adlered** [comment]
非常感谢！！:green_heart:
