### ISSUE TITLE
Email Subscription Needed

### ISSUE THREAD

**Issue by LinHeLurking** [mashirozx/Sakura#207]
**Is your feature request related to a problem? Please describe.**
I was using the plugin "Email Subscribers & Newsletters" to inform my audiences when new posts were created. However this plugin seems to be incompatible with the theme Sakura. Therefore I think it is useful to provide some sort of email subscription services. 

**Describe the solution you'd like**
Provide compatibility with certain email subscription plugins.  

**Describe alternatives you've considered**
Implement built-in email subscription funtions.

Thanks!

**Comment by mashirozx** [comment]
You should either uncheck the **pjax reload** feature in the theme options list, or add the plugin's JS functions to *pjax reload function area* in `sakura-app.js`.

**Comment by LinHeLurking** [comment]
@mashirozx I've tried unchecking the pjax reload but it didn't work. And when I tried to add that plugin's JS functions to _pjax reload function block_, i found that there are only some PHP files in the plugin directory and I cannot figure out how to handle them. Maybe it's not the pjax' fault?

**Comment by mashirozx** [comment]
Does the plugins provide a widget method?

**Comment by LinHeLurking** [comment]
I found that after turning on widget in  Sakura settings, I can add subscribe block now. Sorry for bothering.
