### ISSUE TITLE
gravatar的国内镜像挂了，加载超时，然后破图

### ISSUE THREAD

**Issue by Simon921** [mashirozx/Sakura#208]
gravatar的国内镜像挂了，会重定向到en.gravatar，但是是错链，最终加载超时，显示破图，
mashiro的网站上也是如此
就这个目录出的问题，https://gravatar.2heng.xin/avatar/XXXX

本来WP Acceleration for China 这个插件是可以选不同的国内的镜像的，但改了之后还是会被sakura的主题覆盖掉，导致仍然打开gravatar.2heng.xin/avatar/XXXX

 - Sakura 主题版本 最新的

**Comment by mirai-mamori** [comment]
> gravatar的国内镜像挂了，会重定向到en.gravatar，但是是错链，最终加载超时，显示破图，
> mashiro的网站上也是如此
> 就这个目录出的问题，https://gravatar.2heng.xin/avatar/XXXX
> 
> 本来WP Acceleration for China 这个插件是可以选不同的国内的镜像的，但改了之后还是会被sakura的主题覆盖掉，导致仍然打开gravatar.2heng.xin/avatar/XXXX
> 
> * Sakura 主题版本 最新的

手动先替换回CN源或者国内的一些镜像源（V2EX、Geekzu）吧
