### ISSUE TITLE
那个bangumi追番页面的cookie怎么弄

### ISSUE THREAD

**Issue by FlandreScarle7** [mashirozx/Sakura#218]
为什么填了cookie没有效果,带"和不带"都试过。

**Comment by spirit1431007** [comment]
把获取到的cookies全部填入即可

**Comment by FlandreScarle7** [comment]
获取到的cookie是这样的"xxxx", 请问需不需要把引号去掉，还有就是默认状态下前面有一串英文，我把那串英文删除了有影响吗

**Comment by spirit1431007** [comment]
cookie并不是这样的哦，你可以这样获取：
浏览器F12，打开https://space.bilibili.com/ ，在 `network` 栏的 `filter` 中搜索你的uid，点击后可以在 `Headers` 一栏看见你的cookie，一般是以`LIVE_BUVID=`打头的，你只需把 `Cookie` 的值全部复制进后台设置就可以了

**Comment by FlandreScarle7** [comment]
原来如此，我之前一直是用document.cookie获取的，难怪不一样。

**Comment by FlandreScarle7** [comment]
谢谢你！

**Comment by spirit1431007** [comment]
不客气
