### ISSUE TITLE
登录或注册界面的滑块，电脑端滑动过快，滑块会回到开始

### ISSUE THREAD

**Issue by ITTWTTI** [mashirozx/sakura#221]
**描述问题**
登录或注册界面的滑块，电脑端滑动过快，滑块会回到开始
手机端部分浏览器滑动滑块时，会返回到上一页（eg.小米原生浏览器）
手机用Chrome浏览器是则没有这样的问题

**系统信息**
 - （前端）操作系统: [Windows 10, MIUI10]
 - 浏览器: [chrome]
 - PHP 版本7.3
 - WordPress 版本5.3
 - Sakura 主题版本3.3.8

**补充信息**
希望作者可以加入其他的验证方式，比如十位数数学运算等

**Comment by mashirozx** [comment]
那是手机上开启了左右滑动返回/前进的功能了吧

**Comment by ITTWTTI** [comment]
> 那是手机上开启了左右滑动返回/前进的功能了吧
嗯嗯，但是现在大多数人手机上可能都是这么设定，所以我想在使用中可能不太方便。

**Comment by ITTWTTI** [comment]
> 那是手机上开启了左右滑动返回/前进的功能了吧

所以能不能加上其他的验证方式，或者直接从代码上禁用这个功能，主题后台的禁用试过了，发现没有效果
电脑端则是鼠标点中滑块，后滑的太快，滑块就会回到起始位置

**Comment by mashirozx** [comment]
以后抽空换成极验之类的吧

**Comment by otherbanana** [comment]
请问一下，有办法禁用这个滑块吗？
