### ISSUE TITLE
content.js lib.js 和 sakura-app.js 里涉及到googlefonts的地方，可不可以也变成可选国内镜像的

### ISSUE THREAD

**Issue by Simon921** [mashirozx/Sakura#222]
sakura-app.js:1077行
content.js:2行
lib.js:33行
这三处不翻墙的话都会Loading好久，直到超时
建议像上次gravatar的优化一样，在后台加入可选国内镜像的选项，极客族之类的
<img width="1219" alt="WX20200420-014945@2x" src="https://user-images.githubusercontent.com/12639565/79695560-1fee8d00-82aa-11ea-8d0a-dae316317b2f.png">

**Comment by mirai-mamori** [comment]
理论可行（

**Comment by mashirozx** [comment]
Google服务器在国内，无需多此一举
![image](https://user-images.githubusercontent.com/16148054/79896503-0d578d80-843b-11ea-9337-8ab69cd05a6e.png)

**Comment by Simon921** [comment]
> Google服务器在国内，无需多此一举
> ![image](https://user-images.githubusercontent.com/16148054/79896503-0d578d80-843b-11ea-9337-8ab69cd05a6e.png)

呃 那截图里的超时是什么原因造成的呢

**Comment by mashirozx** [comment]
检查一下是不是改过hosts，或者就是当地的宽带线路问题。googleapis在上海和北京都有服务器，我认为无论是速度还是稳定性都应该是比第三方镜像强的。

**Comment by Simon921** [comment]
雾草……
我说怎么google analytics我这儿连接也有问题呢……
破案了……
在遥远的2015年我加过一组Google hosts……………………
这个话题可以终结了……
谢谢mashiro
