### ISSUE TITLE
首页文章显示和分页相关

### ISSUE THREAD

**Issue by AnimatorBullet** [mashirozx/Sakura#224]
**描述问题**
1. 文章总数10，有置顶文章，主页显示文章数9，有下一页，但是404
2. 文章总数10，无置顶文章，主页显示文章数10，无下一页
3. 文章总数11，有置顶文章，主页显示文章数9，有下一页，但是第2篇文章不显示，加载后只有10篇文章
4. 文章总数11，无置顶文章，主页显示文章数10，有下一页，显示完整11篇文章

（另外有个不知道是不是问题，后台“阅读”里面设置主页显示文章数并不起效）
（固定连接改成/%postid%.html，文章会变404，不过这可能是我设置问题-。-
换成%posename%.html是OK的）

**bug 重现步骤**

**截图（如有）**

**系统信息**
 - （前端）操作系统: [Windows 10]
 - 浏览器: [chrome]
 - PHP 版本
 - WordPress 版本
 - Sakura 主题版本：3.3.8

**补充信息**

**Comment by spirit1431007** [comment]
文章总数为10的话所有文章都会在首页显示，我认为没有必要置顶

**Comment by mashirozx** [comment]
的确我们应该规范一下输出，不过这是重构议程里面的事了，目前暂时避免十篇文章还带置顶的情况吧🤔

**Comment by AnimatorBullet** [comment]
因为后台其实有设置首页显示文章数，所以原本没想首页全部显示完，
不过现在把wordpress官方后台阅读里面的设置改成10可以解决问题。

**Comment by MuenYu** [comment]
分页文章数量与后台设置——“博客页面至多显示”设置数量不符。
