### ISSUE TITLE
如何在升级的时候保留以前的配置文件

### ISSUE THREAD

**Issue by lixuedong1024** [mashirozx/Sakura#225]
用过之前版本的主题  
看到有新的版本 
如何在保留以前的配置文件的前提下进行更新呢

**Comment by spirit1431007** [comment]
直接覆盖主题文件即可。

**Comment by lixuedong1024** [comment]
好的  多谢回复

Spirit <notifications@github.com> 于2020年5月11日周一 上午8:09写道：
