### ISSUE TITLE
如果可以的话，请修一下markdown关于代码块的部分吧

### ISSUE THREAD

**Issue by IAbu0288** [mashirozx/Sakura#226]
1.在`[` `github repo="mashirozx/Sakura"` `]`中，如果不手动更改html代码块就会自动变成<code>[github repo="mashirozx/Sakura"]</code>这样的话wordpress会将它作为短代码执行(形容的可能不是很好)
2.在
``` cpp
内容
```
![image](https://user-images.githubusercontent.com/48312963/81978233-cb96bd00-965d-11ea-9bab-d2ea3b9dd2b2.png)
中会自动变成
``` text
cpp
内容
```
![image](https://user-images.githubusercontent.com/48312963/81978258-d5202500-965d-11ea-81d8-9beaf8f23ffa.png)
虽然也有解决办法：在markdown编辑器中编辑导出html格式复制到wordpress。
设想的解决方案：
1.修改或禁用WP Editor.md中关于代码块的部分来避开与主题自带的代码块冲突。(顺便支持WP Editor.md)
2.优化主题自带markdown代码块相关
3.直接兼容WP Editor.md并保留主题内的MAC风格代码块样式

不是我不想整，而是我不知道怎么整...如果涉及到的工程量比较大的话那就无所谓了，麻烦就麻烦一点吧，但是还是希望方便一丢丢的

**Comment by spirit1431007** [comment]
注意规范：
<pre>
<code>
方括号前后无空格
 `[github repo="mashirozx/Sakura"]` 

```后直接写语言，无空格
```cpp
内容
```

</code>
</pre>

**Comment by IAbu0288** [comment]
emm
首先是[github repo="mashirozx/Sakura"]，如果不把他们的[和]分开的话就会作为短代码输出
![image](https://user-images.githubusercontent.com/48312963/82027125-56ab9d80-96c6-11ea-9109-91cbdf762250.png)
然后代码块
![dmk](https://user-images.githubusercontent.com/48312963/82028414-2f55d000-96c8-11ea-978f-ce94bc0acf92.gif)

**Comment by IAbu0288** [comment]
另外，关于`!{}[]`相册功能，个人觉得可以直接替换掉原有的`![]()`

**Comment by spirit1431007** [comment]
> emm
> 首先是[github repo="mashirozx/Sakura"]，如果不把他们的[和]分开的话就会作为短代码输出
> ![image](https://user-images.githubusercontent.com/48312963/82027125-56ab9d80-96c6-11ea-9109-91cbdf762250.png)
> 然后代码块
> ![dmk](https://user-images.githubusercontent.com/48312963/82028414-2f55d000-96c8-11ea-978f-ce94bc0acf92.gif)

看图片里，你使用的是区块编辑器。github-card是通过伪短代码实现的，最好使用便编辑源代码的方式书写；另外，区块编辑器与markdown语法不兼容

**Comment by spirit1431007** [comment]
> 另外，关于`!{}[]`相册功能，个人觉得可以直接替换掉原有的`![]()`
> 因为写好md后还要手动替换，虽然不替换也一样用。但是，既然有这个功能为什么不用呢(滑稽)

因为要兼容主题老版本使用的baguetteBox

**Comment by spirit1431007** [comment]
主题是兼容WP Editor.md的，更多用法详情 https://sakurasaku.cn/d/4-wp-editormd-sakura

**Comment by IAbu0288** [comment]
> github-card是通过伪短代码实现的，最好使用便编辑源代码的方式书写；另外，区块编辑器与markdown语法不兼容

对于这个我的解决方案是在Typora里编辑完后导出html复制到wp编辑器里，或者是在Typora里编辑完后直接复制到区块编辑器里再修改

**Comment by IAbu0288** [comment]
> 主题是兼容WP Editor.md的，更多用法详情https://sakurasaku.cn/d/4-wp-editormd-sakura

感谢分享

**Comment by spirit1431007** [comment]
> 对于这个我的解决方案是在Typora里编辑完后导出html复制到wp编辑器里，或者是在Typora里编辑完后直接复制到区块编辑器里再修改

你可以在Typora里编辑完后直接复制到WP Editor.md
