### ISSUE TITLE
修改 donate.ejs

### ISSUE THREAD

**Issue by SnorlaxSE** [mashirozx/Sakura#227]
**描述问题**
”赞赏页面“  用户名显示的是 hojun（如图1）   希望更改为自定义的用户名，修改donate.ejs相应信息  终端会有异常提示（如图2）  不知怎么处理
**bug 重现步骤**

**截图（如有）**
![图1](https://user-images.githubusercontent.com/19644938/82010087-ae84dd00-96a3-11ea-833f-17704377bf5c.png)

![图2](https://user-images.githubusercontent.com/19644938/82010091-afb60a00-96a3-11ea-8468-cacaaf6b8812.png)

**系统信息**
 - 操作系统: macOS Catalina 10.15.4
 - 浏览器: chrome

**Comment by mashirozx** [comment]
这里是wordpress版主题仓库
