### ISSUE TITLE
zoom 放大图片修改 无效

### ISSUE THREAD

**Issue by SnorlaxSE** [mashirozx/Sakura#228]
**描述问题**
按描述修改`Sakura\node_modules\marked\lib\marked.js`后， 图片依旧无法放大

![image](https://user-images.githubusercontent.com/19644938/82010263-2d7a1580-96a4-11ea-8d77-63b91ed0624e.png)

**Comment by spirit1431007** [comment]
Hexo版请在 https://github.com/honjun/hexo-theme-sakura 处发issue
