### ISSUE TITLE
Highlight.js 的 data-rel 设置不正确

### ISSUE THREAD

**Issue by CHN-beta** [mashirozx/Sakura#235]
**描述问题**：

使用 wordpress 自带编辑器，插入代码区块后，发布后可以探测到语言（cpp），但是 `data-rel` 总是被设置为 `TEXT`，导致高亮正常，但显示的语言不对。如图所示。

![image](https://user-images.githubusercontent.com/35858462/88085644-b8055680-cbb8-11ea-9603-779666b2280d.png)

**重现步骤**：

* 新安装 wordpress
* 正确安装 Sakura 主题
* 使用自带编辑器，随便写句代码，发布。

**系统信息**：

* 前、后端操作系统：均为 Archlinux，滚到最新。
* 浏览器：Chromium 版本 84.0.4147.89（正式版本）Arch Linux （64 位）
* PHP 版本：7.4.8
* WordPress 版本：5.4.2–zh_CN
* Sakura 主题版本：当前 master 分支最新
* 其它插件：没，都没装

**Comment by cllllll** [comment]
用markdown编辑器 markdown标准语法 别用自带的------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;陈浩南&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月22日(星期三) 凌晨1:22
收件人:&nbsp;&quot;mashirozx/Sakura&quot;<Sakura@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[mashirozx/Sakura] Highlight.js 的 data-rel 设置不正确 (#235)

**Comment by CHN-beta** [comment]
> 用markdown编辑器 markdown标准语法 别用自带的------------------&nbsp;原始邮件&nbsp;------------------
> 发件人:&nbsp;&quot;陈浩南&quot;<notifications@github.com&gt;
> 发送时间:&nbsp;2020年7月22日(星期三) 凌晨1:22
> 收件人:&nbsp;&quot;mashirozx/Sakura&quot;<Sakura@noreply.github.com&gt;;
> 抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
> 主题:&nbsp;[mashirozx/Sakura] Highlight.js 的 data-rel 设置不正确 (#235)

感谢回复。

个人不喜欢用 md 写博客，所以现在是在 `functions.php` 里加了一段 js 来从 class 里提取字符串赋值给 data-rel。可以用，但觉得这样的写法可能不够标准。请问是否有更优雅规范的实现方式？
