### ISSUE TITLE
打扰了，页面有点问题

### ISSUE THREAD

**Issue by lteyox** [mashirozx/Sakura#238]
**描述问题**
edge，谷歌浏览器在窗口化窗口时菜单栏错位或直接不显示主文字，页面。
**bug 重现步骤**
窗口化窗口，点击菜单在767x823状态下不显示页面文字，在1028x823状态下菜单错位
**截图（如有）**
![image](https://user-images.githubusercontent.com/57826838/89710906-7d256000-d9b9-11ea-9bbf-d371102ff3ac.png)
![image](https://user-images.githubusercontent.com/57826838/89711027-426ff780-d9ba-11ea-8e51-2378ed19775b.png)
![image](https://user-images.githubusercontent.com/57826838/89711054-63384d00-d9ba-11ea-957e-befdae37840a.png)

**系统信息**
 - （前端）操作系统: [e.g. Windows 10, Android 9.0]
 - 浏览器: [e.g. chrome, safari]
 - PHP 版本:7.2
 - WordPress 版本:5.3.2
 - Sakura 主题版本:Theme Sakura v 3.3.8

**补充信息**

**Comment by mashirozx** [comment]
菜单项目过长时会触发这个问题，我自己博客上针对这个问题处理过，但是只是针对特定宽度的菜单的处理，所以建议精简菜单，或者参考我的主页自行调一下样式

**Comment by lteyox** [comment]
谢谢
