### ISSUE TITLE
Readme 的小图标挂了😂

### ISSUE THREAD

**Issue by mashirozx** [mashirozx/sakura#243]
**描述问题**

**bug 重现步骤**

**截图（如有）**

**系统信息**
 - （前端）操作系统: [e.g. Windows 10, Android 9.0]
 - 浏览器: [e.g. chrome, safari]
 - PHP 版本
 - WordPress 版本
 - Sakura 主题版本

**补充信息**

**Comment by spirit1431007** [comment]
了解👌

**Comment by lmeng-786** [comment]
页脚的音乐播放是怎么设置的，我添加的小工具页面非常大
windows10
chrome
PHP 7.1.31 
wordpress  5.0.3
![微信图片_20200828101847](https://user-images.githubusercontent.com/70270567/91513840-e3960200-e917-11ea-836b-375f3e4642a5.png)
