### ISSUE TITLE
[求助]对第一屏的设置无法生效

### ISSUE THREAD

**Issue by chaliliiiiiiii** [mashirozx/Sakura#244]
描述问题
配置主题时"Sakura主题设置>第一屏>封面图片库选项"选择了"外部随机图API",正确填写了"封面图片库URL"并保存设置,但是主页第一屏始终无法显示图片;
打开Dev Tools查看,封面图片的地址是"https://我的域名/wp-json/sakura/v1/image/cover",然而网站根目录下并没有wp-json文件夹(是主题自动生成的吗,小白对wp和rest api的机制完全不清楚);
目前是nginx做了rewrite指向了API地址,但是我想知道为何会出现这种情况,以及如何解决这一问题;

系统信息
-(前端)操作系统: Windows10
-浏览器: chrome
-PHP版本: 7.2
-WordPress版本: 5.4.2
-Sakura主题版本: 3.3.9

补充信息
尝试过将"封面图片库"设置为"webp优化随机图/内置原图随机图/外部随机图API",都无法生效,Dev Tools显示地址均为"https://我的域名/wp-json/sakura/v1/image/cover"
也试过将插件全部禁用再设置，依旧如此
感谢作者解答[鞠躬]

**Comment by mashirozx** [comment]
很大可能是其他插件禁用了wp-json路由，建议先关闭其他插件以逐一排除

**Comment by chaliliiiiiiii** [comment]
> 很大可能是其他插件禁用了wp-json路由，建议先关闭其他插件以逐一排除

感谢作者的热心帮助
是这样的，我尝试过将所有插件禁用再进行设置、保存，但情况依旧如此：wp-json文件夹仍未生成

**Comment by mashirozx** [comment]
可以看一下 https://domain/wp-json 能不能打开

**Comment by chaliliiiiiiii** [comment]
> 可以看一下 https://domain/wp-json 能不能打开

显示404 not found，网站根目录也没有这个文件夹

**Comment by spirit1431007** [comment]
https://www.wpdaxue.com/wordpress-rewriterule.html

**Comment by chaliliiiiiiii** [comment]
> https://www.wpdaxue.com/wordpress-rewriterule.html

抱歉这么迟才回复，这个解决方案尝试有效，感谢大佬！
就是有点好奇这是怎么生效的，看这个帖子里是尝试把网页指向到index.php，并且把参数传递过去（之前我的配置是指向404页），这是rest api的工作原理吗，大佬愿意的话可以指点一下吗

**Comment by spirit1431007** [comment]
> > https://www.wpdaxue.com/wordpress-rewriterule.html
> 
> 抱歉这么迟才回复，这个解决方案尝试有效，感谢大佬！
> 就是有点好奇这是怎么生效的，看这个帖子里是尝试把网页指向到index.php，并且把参数传递过去（之前我的配置是指向404页），这是rest api的工作原理吗，大佬愿意的话可以指点一下吗

配置伪静态只是重写了下url，非朴素的固定链接wp-rest-api的url是 https://domain/wp-json，朴素的url是https://domain/index.php?rest_route=
