### ISSUE TITLE
以用户头像触发的下拉菜单

### ISSUE THREAD

**Issue by RJCooLEST** [mashirozx/sakura#245]
在博客网页手动进入后台设置时，触发下拉菜单的个人头像与下拉菜单之间存在一些间隙，容易导致下拉菜单没有互动后消失，且消失的速度很快，算是操作不太方便把（。

设置较大的判定区域，和悬停一段时间都能改善这种情况。（表示不是很懂弄

还原如下：
![123](https://user-images.githubusercontent.com/56374469/92468113-3a97b300-f205-11ea-898a-badc1116da6d.gif)

**Comment by Hubray** [comment]
啊啊啊，这个我也发现了，而且很容易触发

经常出现想进后台，鼠标移动到头像，出现下拉菜单，然后鼠标下移动，下拉菜单消失.....
