### ISSUE TITLE
[Enhancement] Allow customizing the URL for loading googlefonts

### ISSUE THREAD

**Issue by yezhiyi9670** [mashirozx/Sakura#246]
**Is your feature request related to a problem? Please describe.**

fonts.googleapis.com cannot be properly accessed under some networks in China. This leads to ugly system fonts being showed on the page. The URL is hardcoded in sakura-app.js, which is on a CDN hosted by you, so it will be a great deal to change it.

I've already had a alternative of google fonts. We can use something we call *tizi* and grab the fonts and CSS from fonts.googleapis.com. Then we just upload it to Github so that we can use it through jsDelivr. [This](https://cdn.jsdelivr.net/gh/yezhiyi9670/akioi-cdn/fonts/SakuraFonts-v5/index.css) is an example which works almost perfectly.

**Describe the solution you'd like**

Allow changing the font URL in the theme settings.

**Comment by spirit1431007** [comment]
#222
