### ISSUE TITLE
怎么更改主页面搜索中的人物图像？

### ISSUE THREAD

**Issue by lyryblog** [mashirozx/Sakura#248]
#像这样的人物：
![B4D00A74-E75A-4f28-ADA0-0450D9975CE7](https://user-images.githubusercontent.com/61700209/94857053-7a983180-0463-11eb-9a85-6d67cd87c771.png)

**Comment by lyryblog** [comment]
![B4D00A74-E75A-4f28-ADA0-0450D9975CE7](https://user-images.githubusercontent.com/61700209/94857135-98fe2d00-0463-11eb-8bde-29cf38bae8e1.png)

**Comment by lyryblog** [comment]
人物图片链接
https://cdn.jsdelivr.net/gh/moezx/cdn@3.2.1/img/other/iloli.gif

**Comment by mashirozx** [comment]
f12 解千愁

**Comment by mashirozx** [comment]
https://github.com/mashirozx/Sakura/search?q=https%3A%2F%2Fcdn.jsdelivr.net%2Fgh%2Fmoezx%2Fcdn%403.2.1%2Fimg%2Fother%2Filoli.gif&type=

**Comment by lyryblog** [comment]
找了很久，终于找到了！
![image](https://user-images.githubusercontent.com/61700209/94961056-8862bb00-0526-11eb-8e68-cd2b37acbc82.png)

**Comment by lyryblog** [comment]
> https://github.com/mashirozx/Sakura/search?q=https%3A%2F%2Fcdn.jsdelivr.net%2Fgh%2Fmoezx%2Fcdn%403.2.1%2Fimg%2Fother%2Filoli.gif&type=

啊这......

**Comment by lyryblog** [comment]
> f12解千愁

我之前也看到过，不然我也不会找出这个链接
就是位置不知道在哪，在一大堆PHP中找了好久
总之还是谢谢白猫！
（还有2heng.xin出现Error 520错误，修复好后回复我的评论呗。@RYlo，谢谢）
