### ISSUE TITLE
highlightjs不支持kotlin?

### ISSUE THREAD

**Issue by dylech30th** [mashirozx/Sakura#249]
![image](https://user-images.githubusercontent.com/31894334/95494763-fef13400-09d0-11eb-8104-1495159ff02a.png)
![image](https://user-images.githubusercontent.com/31894334/95494750-fac51680-09d0-11eb-8ec0-3b7685d1d68e.png)

已经关闭了WP editor.md的所有highlight选项，同时尝试把源文件目录下的cdn/src/js/highlight.pack.js和highlightjs-line-number.js更新到了官网的最新版本

**Comment by dylech30th** [comment]
将代码换成其他语言之后语法高亮正常，例：
![image](https://user-images.githubusercontent.com/31894334/95495557-2f859d80-09d2-11eb-9e97-8ad9c5055e53.png)
![image](https://user-images.githubusercontent.com/31894334/95495541-2b598000-09d2-11eb-86b5-efe09dc07b63.png)

**Comment by mashirozx** [comment]
需要单独引入一下highlightjs相应语言的适配代码

主题里面没有引入kotlin的

**Comment by dylech30th** [comment]
我在highlight.js的官网上看到新版本是支持kotlin的...然后我尝试把新版本下载下来替换了文件夹里的highlight.pack.js，我在本地测试了一下新版本是可以渲染kotlin的，如图
![image](https://user-images.githubusercontent.com/31894334/95498930-1c290100-09d7-11eb-8934-8b8a9331273b.png)
![image](https://user-images.githubusercontent.com/31894334/95498947-25b26900-09d7-11eb-9482-fd1b27302256.png)
但是我替换的文件在前端却没有起到作用，请问是我替换错了吗？

**Comment by dylech30th** [comment]
![image](https://user-images.githubusercontent.com/31894334/95499114-60b49c80-09d7-11eb-8e89-b97f6d8a0951.png)
就是这里这个

**Comment by mashirozx** [comment]
你需要用那个Python脚本合并一下lib代码
里面的js都压缩到lib.js里面了

**Comment by dylech30th** [comment]
忘了调用的不是本地的lib.js这茬，最新版的highlight.js代码换了，不能直接合并，要自己先处理一下，否则会出错，不过问题还是解决了

**Comment by dylech30th** [comment]
btw刚刚发送了友链请求，不嫌弃的话希望能得到通过((
