### ISSUE TITLE
增加一个不显示文章封面图的功能

### ISSUE THREAD

**Issue by wlmqpsc** [mashirozx/Sakura#251]
**Is your feature request related to a problem? Please describe.**
我目前采用外部api的方式，调取文章封面图（文章特色图片），每张图片600kb左右。同时请求多个图片对服务器造成了不小的负担。
如果采用跟随封面图的方式，在图片未加载完成时，前几个文章的图片是一样的。
**Describe the solution you'd like**
1、增加一个关闭文章封面图选项
2、从另一个目录读取webp优化图，与博客封面图片不重复
**Describe alternatives you've considered**

**Additional context**
如果可以的话，在调用外部api时，增加一个apikey选项

**Comment by BingChunMoLi** [comment]
文章封面优先特色图片，如果没有才会请求API

**Comment by spirit1431007** [comment]
文章不设置封面图就好～这样就会调用api的图片
