### ISSUE TITLE
显示代码块的时候，代码都合在一行里了。。。

### ISSUE THREAD

**Issue by lwy156** [mashirozx/Sakura#256]
**描述问题**

**bug 重现步骤**

**截图（如有）**

**系统信息**
 - （前端）操作系统: [e.g. Windows 10, Android 9.0]
 - 浏览器: [e.g. chrome, safari]
 - PHP 版本
 - WordPress 版本
 - Sakura 主题版本

**补充信息**

**Comment by BingChunMoLi** [comment]
插件冲突问题，关闭插件的高高亮等功能即可解决，因为主题自带了语法高亮，行号显示等功能

**Comment by spirit1431007** [comment]
主题自带了语法高亮功能，请关闭相关wp插件的相关功能
