### ISSUE TITLE
Switch From Adobe Typekit to Google Fonts!

### ISSUE THREAD

**Issue by hifocus** [mashirozx/Sakura#26]
Google Fonts had been supporting Chinese fonts for two months. Both Noto Sans and Noto Serif is supported. Please see https://fonts.google.com/?subset=chinese-simplified.

We all know that Google Fonts (Beijing & Shanghai BGP Datacenters) or its mirror site fonts.loli.net  (Aliyun CDN) behave rather excellent in both China Mainland and other regions. But Adobe Typekit uses Akamai CDN which is not optimised in China and furthermore it does have multiple restrictions for free users. 

So I would consider loading the Noto Serif that "Sakura" uses from Google Fonts (especially from fonts.loli.net will be a better solution). In addition, it does not require the users to register an Adobe ID to get the limited access to Typekit anymore!

**Comment by mashirozx** [comment]
Thanks for letting me know, looking forward to Google Fonts' supporting for Source Han Serif.

**Comment by hifocus** [comment]
Source Han Serif = Noto Sans Serif

It seems that two companies are using different names, but the thing is Google Fonts is currently supporting Chinese Simplified

![image](https://user-images.githubusercontent.com/30528433/50485303-c4065200-0a2f-11e9-9059-f607930a66e2.png)

That is the point for this issue. I would consider submitting several changes as a Pull Request. It's currently in progress.

**Comment by mashirozx** [comment]
@hifocus https://source.typekit.com/source-han-serif/cn/

**Comment by hifocus** [comment]
Please refer to https://free.com.tw/google-fonts-noto-sans-tc/ , they are the same

**Comment by hifocus** [comment]
Thanks for taking my point.
