### ISSUE TITLE
开启WP-Statistics插件后，前端的热度一直显示为0

### ISSUE THREAD

**Issue by zxbzxb180** [mashirozx/Sakura#260]
请问一下，在主题设置中开启WP-Statistics插件后，在后台能看到点击量，但是前端的热度一直是0，是还需要设置什么地方吗？

**Comment by spirit1431007** [comment]
管理员登录后的点击会被自动过滤

**Comment by zxbzxb180** [comment]
> 管理员登录后的点击会被自动过滤

你好，实际上我已经把管理员过滤给取消掉了，插件后台也是可以看到站点的访问量的。我在未登录的情况下查看文章后，热度仍然显示为0。而在使用主题默认的统计时，热度是正常显示的。

**Comment by spirit1431007** [comment]
是否装有缓存优化插件

**Comment by zxbzxb180** [comment]
> 是否装有缓存优化插件

好像装过，不过已经被我删除了，需要安装缓存优化插件吗

**Comment by spirit1431007** [comment]
不用安装，如果清除缓存（CDN和浏览器的缓存）刷新网页，访问文章后点击次数显示的还是0请排查是否是安装了其他插件的问题  
排查步骤：依次禁用相关插件，再访问文章，看看点击数是否增加

**Comment by zxbzxb180** [comment]
> 不用安装，如果清除缓存（CDN和浏览器的缓存）刷新网页，访问文章后点击次数显示的还是0请排查是否是安装了其他插件的问题
> 排查步骤：依次禁用相关插件，再访问文章，看看点击数是否增加

我把除了WP-statistic的所有插件都禁用了，清除缓存，再访问文章，点击数依然没有增加。。
