### ISSUE TITLE
使用本主题后，markdown感觉支持的不友好

### ISSUE THREAD

**Issue by dayu-hang** [mashirozx/Sakura#262]
比如 "> " 引用符号，在这里显示的不是引用，而是两个特别大的引号

**Comment by Tsaiyq** [comment]
谢了哈------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;dayu-hang&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年2月4日(星期四) 凌晨2:07
收件人:&nbsp;&quot;mashirozx/Sakura&quot;<Sakura@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[mashirozx/Sakura] 使用本主题后，markdown感觉支持的不友好 (#262)

**Comment by spirit1431007** [comment]
引用的样式就是引号

**Comment by dayu-hang** [comment]
![image](https://user-images.githubusercontent.com/55073294/106835603-942bdd00-66d2-11eb-9356-8bd1d2f319f3.png)

**Comment by dayu-hang** [comment]
![image](https://user-images.githubusercontent.com/55073294/106835645-a443bc80-66d2-11eb-9536-ed9dbad8beac.png)
现在使用是这样子
![image](https://user-images.githubusercontent.com/55073294/106835701-c63d3f00-66d2-11eb-837f-f9edcaf2d9c1.png)
编写文章是这个样子，我如何让前台显示也是这样子呢？
辛苦帮忙看看，非常感谢

**Comment by mashirozx** [comment]
正文样式不是有两套可以选吗

**Comment by mashirozx** [comment]
https://sakura.2heng.xin/2018/05/25/markdown/

**Comment by mashirozx** [comment]
正文样式不是有两套可以选吗
https://sakura.2heng.xin/2018/05/25/markdown/
另外那套是Github风格的

**Comment by dayu-hang** [comment]
非常感谢。已经成功设置！
