### ISSUE TITLE
主题ssl化   总显示混合  插件也解决不了

### ISSUE THREAD

**Issue by mantoubuxiang** [mashirozx/sakura#263]
在安全的加密网页中载入混合（不安全的）显示内容“http://m701.music.126.net/20210307232007/72653de1bba7a7fbc00eea6f4ab01967/jdymusic/obj/w5zDlMODwrDDiGjCn8Ky/1726655982/9c91/e31c/8bef/b9bcb9a6c7fb0996eba8bb3d38c66860.mp3”

**Comment by mashirozx** [comment]
![image](https://user-images.githubusercontent.com/16148054/110244538-21947280-7f9a-11eb-9c05-1afbcc40d86a.png)
未能复现。是否是主题自带的播放器加载的音乐？

**Comment by mantoubuxiang** [comment]
> 
> 
> ![图像](https://user-images.githubusercontent.com/16148054/110244538-21947280-7f9a-11eb-9c05-1afbcc40d86a.png)
> 未能复现。是否是主题自带的播放器加载的音乐？

对 就是播放器的音乐 我改了svg中的http为https
貌似就可以

**Comment by mantoubuxiang** [comment]
> 
> 
> ![图像](https://user-images.githubusercontent.com/16148054/110244538-21947280-7f9a-11eb-9c05-1afbcc40d86a.png)
> 未能复现。是否是主题自带的播放器加载的音乐？

就是这个   不知道在哪个位置改呀  求大佬明示

**Comment by mashirozx** [comment]
据我所知不用改吧，默认都是https的好像

**Comment by mantoubuxiang** [comment]
> 
> 
> 据我所知不用改吧，默认都是https的好像

liuhao.live  帮忙看下呢  麻烦您了 谢谢

**Comment by mantoubuxiang** [comment]
> 
> 
> 据我所知不用改吧，默认都是https的好像

liuhao.live   
帮忙看下呢麻烦您了谢谢
