### ISSUE TITLE
代码块显示不正确

### ISSUE THREAD

**Issue by DyNooob** [mashirozx/Sakura#265]
**代码块显示不正确**

我在发布文章时使用Markdown写的代码块
![image](https://user-images.githubusercontent.com/77604429/112748115-5a999300-8fec-11eb-978f-45486d55d226.png)

这是发布后
![image](https://user-images.githubusercontent.com/77604429/112748134-79982500-8fec-11eb-9331-ebba4c1e7940.png)

**系统信息**
 - Nginx
 - 浏览器: Chrome，Edge
 - PHP7.2
 - WordPress 5.7
 - Sakura v 3.3.9

**Comment by BaoYi-9527** [comment]
Markdown不兼容 关闭Wordpress的markdown插件就可以了&nbsp;




张韦程
财盈通


 联系我









&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月28日(星期天) 下午5:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mashirozx/Sakura] 代码块显示不正确 (#265)





 
代码块显示不正确
 
我在发布文章时使用Markdown写的代码块
 
 
这是发布后
 
 
系统信息
  
Nginx
 
浏览器: Chrome，Edge
 
PHP7.2
 
WordPress 5.7
 
Sakura v 3.3.9

**Comment by DyNooob** [comment]
那是不是意味着我以后发完就要关闭插件。。

**Comment by BaoYi-9527** [comment]
并非如此，主题有自己的Markdown渲染方式，关闭的是Wordpress的Markdown插件
&nbsp;




张韦程
财盈通


 联系我









&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月28日(星期天) 下午5:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mashirozx/Sakura] 代码块显示不正确 (#265)





 
那是不是意味着我以后发完就要关闭插件。。
