### ISSUE TITLE
Jiathis.com is not available in the theme

### ISSUE THREAD

**Issue by hifocus** [mashirozx/Sakura#27]
I have noticed that Sakura is using `www.jiathis.com` to reach the social sharing function at https://github.com/mashirozx/Sakura/blob/master/layouts/sharelike.php#L24. 

But currently `http://www.jiathis.com/send/?webid=weixin&url=https://example.com` or `http://www.jiathis.com/send/?webid=weixin&url=` is returning a 404 error status code.

```
root@HXCO:~# curl -I http://www.jiathis.com/send/?webid=weixin&url=https://example.com
[1] 9541
root@HXCO:~# HTTP/1.1 404 Not Found
Server: nginx/1.12.2
Date: Thu, 27 Dec 2018 04:23:27 GMT
Content-Type: text/html
Content-Length: 169
Connection: keep-alive
```

Please consider to replace these `www.jiathis.com` APIs to their original ones like `http://service.weibo.com/share/share.php?url=`.

**Comment by mashirozx** [comment]
Yes, seems jiathis.com was closed earlier this year. As an alternative, you may have a look at this: <https://github.com/overtrue/share.js/>

I'll fix this problem latter when I have time.

**Comment by hifocus** [comment]
Why don't you just get those official APIs embed instead of using their-party plugins

**Comment by mashirozx** [comment]
@hifocus For the stability of interface. Believing these third party share services/projects will get timely update.
