### ISSUE TITLE
更新 manifest 跳转 404

### ISSUE THREAD

**Issue by AnimatorBullet** [mashirozx/Sakura#271]
**描述问题**
重新回复的网站，换了服务器，封面图和 manifest 都是以前的，没有问题，点击更新 manifest 跳转 404
**bug 重现步骤**
1.准备好图片和manifest等
2.设置中 点击 这里 更新manifest

**截图（如有）**
![image](https://user-images.githubusercontent.com/45991057/125209223-fb753b00-e2c9-11eb-9ed4-586cc018d9d3.png)

![image](https://user-images.githubusercontent.com/45991057/125209199-d7b1f500-e2c9-11eb-81f2-d3a92b1ad77f.png)

**系统信息**
 - （前端）操作系统: [Windows 11]
 - 浏览器: [chrome]
 - PHP 版本 8.0
 - WordPress 版本  5.72
 - Sakura 主题版本  3.3.9

**补充信息**
url试了没问题

**Comment by mashirozx** [comment]
换成PHP7.4试试

**Comment by AnimatorBullet** [comment]
> 换成PHP7.4试试

行，之前确实不是高版本，刚好重新恢复就安装了新版php...降版本不知道麻烦不，暂时先不处理了，谢谢

**Comment by mashirozx** [comment]
PHP可以多个版本共存，Nginx或者Apache上指定一下版本就可以了

**Comment by AnimatorBullet** [comment]
> PHP可以多个版本共存，Nginx或者Apache上指定一下版本就可以了

破案了，因为伪静态没了，重新给  /usr/local/nginx/conf/vhost/xxxxxx.com.conf  加了伪静态代码就可以显示了，虽然比较迷~

```
location / {
	try_files $uri $uri/ /index.php?$args;
}
 
# Add trailing slash to */wp-admin requests.
rewrite /wp-admin$ $scheme://$host$uri/ permanent;
```
