### ISSUE TITLE
使用自定义外部图api后，手机打开博客封面图片无法显示。

### ISSUE THREAD

**Issue by Curry-wei98** [mashirozx/Sakura#275]
**描述问题**

**bug 重现步骤**

**截图（如有）**

**系统信息**
 - （前端）操作系统: [e.g. Windows 10, Android 9.0]
 - 浏览器: [e.g. chrome, safari]
 - PHP 版本
 - WordPress 版本
 - Sakura 主题版本

**补充信息**

**Comment by mashirozx** [comment]
看一下console有没有什么信息，可能是外部API有防盗链设置
