### ISSUE TITLE
Warning:  Trying to access array offset on value of type bool in

### ISSUE THREAD

**Issue by Enoouo** [mashirozx/Sakura#277]
**描述问题**
Warning:  Trying to access array offset on value of type bool in /www/wwwroot/enoooo.com/wp-content/themes/Sakura/inc/theme_plus.php  on line 286

Warning:  Attempt to read property "ID" on string in /www/wwwroot/enoooo.com/wp-content/themes/Sakura/inc/theme_plus.php  on line 533

Warning:  Attempt to read property "post_content" on string in /www/wwwroot/enoooo.com/wp-content/themes/Sakura/inc/theme_plus.php  on line 538

**截图**
![image](https://user-images.githubusercontent.com/45646273/133870155-db64122b-9267-418c-987f-020091e3758e.png)
![image](https://user-images.githubusercontent.com/45646273/133870159-cddc9619-abf4-4c43-aa67-9d686545305e.png)

**系统信息**
 - 浏览器: chrome
 - PHP 版本 8.0
 - WordPress 版本 5.8.1
 - Sakura 主题版本 v3.4.0

**Comment by mashirozx** [comment]
用php7.4
