### ISSUE TITLE
graph LR写文章的时候能预览，发布后变了代码块

### ISSUE THREAD

**Issue by df13954** [mashirozx/Sakura#278]
**描述问题**
graph LR写文章的时候能预览，发布后变了代码块

**bug 重现步骤**
主题安装后，进入后端写文章，例如以下代码

```
graph LR
getParent-->bringChildToFront
```

**截图（如有）**

写文章预览是这样的

<img width="623" alt="Xnip2021-09-29_14-09-06" src="https://user-images.githubusercontent.com/18607031/135212846-b2091581-a560-45c0-a0e8-c34cbde8d7d5.png">

发布文章后效果图

<img width="903" alt="Xnip2021-09-29_14-08-18" src="https://user-images.githubusercontent.com/18607031/135212916-551d54cf-a330-4f54-8d05-2b1905a9ded3.png">

**系统信息**
 - （前端）操作系统: Mac os 10.15.6
 - 浏览器: [chrome, safari]
 - Sakura 主题版本 最新3.4.0

**补充信息**
网站是docker部署的。
博客地址
http://blog.debuglive.cn/archives/androidtvbringchildtofront-shi-yong-chang-jing

不知道是转格式问题，还是主题问题，如果大佬有解决方案就更好了。如果不是主题问题，可直接关issue。

**Comment by mashirozx** [comment]
主题不兼容这个插件呀

**Comment by df13954** [comment]
> 主题不兼容这个插件呀

不支持这个语法吗

**Comment by mashirozx** [comment]
除了语法，样式什么的都得适配…建议别用这个插件，换成截图吧...

**Comment by df13954** [comment]
> 除了语法，样式什么的都得适配…建议别用这个插件，换成截图吧...

ok，感谢大佬
