### ISSUE TITLE
firefox中提示“复制成功”

### ISSUE THREAD

**Issue by iftrue-cn** [mashirozx/Sakura#280]
**描述问题**
主题在firefox浏览器中滚动条拉到顶部或底部时，会弹出“复制成功”的提示

**bug 重现步骤**
打开网站，用鼠标拖动滚动条到顶部或底部
https://2heng.xin/ 这里当前版本也有此问题

**Comment by mashirozx** [comment]
未能复现，或许是浏览器插件导致的问题
![image](https://user-images.githubusercontent.com/16148054/142829632-262a62ad-1403-47d0-8973-25f4169d4d04.png)

**Comment by iftrue-cn** [comment]
![1](https://user-images.githubusercontent.com/23302166/142956255-25ef6a19-7efb-4cf7-ae73-313b7d228643.png)
![image](https://user-images.githubusercontent.com/23302166/142956312-b82ae46c-7a83-4ce4-9f66-f6f8cac29e30.png)
在多台电脑都是全新安装的firefox，出现一样的现象

卸载重装了64位版，也是一样
![image](https://user-images.githubusercontent.com/23302166/142957767-7d3d1bf0-96b3-48fb-9981-357e3ddff4f8.png)

**Comment by iftrue-cn** [comment]
是用 **鼠标左键** 拖动滚动条到顶部或底部然后放开才会出现，用鼠标中键滑动则不会

**Comment by mashirozx** [comment]
还是没复现QAQ，你电脑上有没有装什么可以自动复制的软件，比如词典自动取词之类的

**Comment by iftrue-cn** [comment]
是的。是有道词典的 划词翻译 导致的。
