### ISSUE TITLE
Gravatar头像代理设置了，似乎没有用

### ISSUE THREAD

**Issue by Hubray** [mashirozx/Sakura#283]
在主题页面里的Gravatar头像代理设置了gravatar.2heng.xin/avatar，

但是查看头像依然是secure.gravatar.com/avatar

装有的插件：
Akismet、Disable Google Fonts、Google XML Sitemaps、WP Statistics、超级缓存

**截图（如有）**

**系统信息**
 - （前端）操作系统: [Windows 10]
 - 浏览器: [chrome]
 - PHP 版本 7.4
 - WordPress 版本 5.8.2
 - Sakura 主题版本 最新

**补充信息**
还有一点补充，我记得Favicon似乎也设置不成，我填了几个url，保存关插件刷新后还是不行，后来用WP自带编辑上传图片设置上了

**Comment by akikohaku** [comment]
可能是前端浏览器缓存导致，尝试在 开发者工具 -> network 中将 disable cache 选中后刷新。
以及原头像代理有时候貌似用不了，推荐一个目前可用的 sdn.geekzu.org/avatar

**Comment by Hubray** [comment]
> 

破案了，刚才我没找到原因，打算强改functions的时候，发现WP面板没有权限

然后回想起来，因为之前用的是GIT安装，可能文件所有权还是root，ssh过去刷新下权限，可以了
