### ISSUE TITLE
JsDelivr的备案没有了

### ISSUE THREAD

**Issue by Janet-Baker** [mashirozx/Sakura#284]
如题，Jsdelivr的备案没有了，在中国大陆的节点也没有了……
现在在中国大陆的速度是奇慢无比的……
像Jsdelivr这么好用的东西最终还是没能活下来。

作为替代，可以找一些别的CDN用用，当然可能只有一些公共的东西了……

**Comment by Janet-Baker** [comment]
虽然尽管国内还能用gitee自动同步github，但是gitee毕竟不是CDN……
当然也可以想方设法的搞一些东西来用，比如往某些公共库或镜像站(科大的、字节跳动的，之类的)塞亿些东西进去

**Comment by mashirozx** [comment]
jsdelivr没有替代了

**Comment by xiaoluobo58** [comment]
现在是2022年5月，jsDelivr已经全面被DNS污染
工信部，对得起我们吗！日内瓦，退钱！

**Comment by mashirozx** [comment]
#290

**Comment by MyGodKnow** [comment]
嗐，先换上fastly.jsdelivr.net用一会罢，但是如果jsdelivr被全面污染那就真的木大了
