### ISSUE TITLE
aplayer一直错误

### ISSUE THREAD

**Issue by AdminXYZ666** [mashirozx/Sakura#291]
从下午开始一直在测试和移动把jsDelivr的文件全部移到我的服务器里，现在基本都弄完了，但是页脚播放器一直显示不出来，和jsDelivr有关的也全改了，找不到 https://cdn.jsdelivr.net/gh/moeplayer/hermit-x@2.9.9/assets/css/APlayer.min.css?ver=2.9.9 和 https://cdn.jsdelivr.net/gh/moeplayer/hermit-x@2.9.9/assets/js/APlayer.min.js?ver=2.9.9 还有 https://cdn.jsdelivr.net/gh/moeplayer/hermit-x@2.9.9/assets/js/hermit-load.min.js?ver=2.9.9 这3个网址在哪里改。
开加速器访问就没问题，但是关了访问就会报错。

我的博客是 https://mihoyo.wiki/ 请各位大佬帮我看看

Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
APlayer.min.js:1 Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
hermit-load.min.js:1 Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
lib.js?ver=3.4.06:302 Live2D 2.1.00_1
lib.js?ver=3.4.06:302 profile : Desktop
lib.js?ver=3.4.06:302   [PROFILE_NAME] = Desktop
lib.js?ver=3.4.06:302   [USE_ADJUST_TRANSLATION] = false
lib.js?ver=3.4.06:302   [USE_CACHED_POLYGON_IMAGE] = false
lib.js?ver=3.4.06:302   [EXPAND_W] = 2
widget.js:1 Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
autoload.js:41 
  く__,.ヘヽ.        /  ,ー､ 〉
           ＼ ', !-─‐-i  /  /´
           ／｀ｰ'       L/／｀ヽ､
         /   ／,   /|   ,   ,       ',
       ｲ   / /-‐/  ｉ  L_ ﾊ ヽ!   i
        ﾚ ﾍ 7ｲ｀ﾄ   ﾚ'ｧ-ﾄ､!ハ|   |
          !,/7 '0'     ´0iソ|    |
          |.从"    _     ,,,, / |./    |
          ﾚ'| i＞.､,,__  _,.イ /   .i   |
            ﾚ'| | / k_７_/ﾚ'ヽ,  ﾊ.  |
              | |/i 〈|/   i  ,.ﾍ |  i  |
             .|/ /  ｉ：    ﾍ!    ＼  |
              kヽ>､ﾊ    _,.ﾍ､    /､!
              !'〈//｀Ｔ´', ＼ ｀'7'ｰr'
              ﾚ'ヽL__|___i,___,ンﾚ|ノ
                  ﾄ-,/  |___./
                  'ｰ'    !_,.:

sakura-app.js?ver=3.4.0:1961  Mashiro  https://2heng.xin/
sakura-app.js?ver=3.4.0:1962  Github  https://github.com/mashirozx
sakura-app.js?ver=3.4.0:846 Uncaught ReferenceError: APlayer is not defined
    at a (sakura-app.js?ver=3.4.0:846)
    at XMLHttpRequest.h.onreadystatechange (sakura-app.js?ver=3.4.0:896)
a @ sakura-app.js?ver=3.4.0:846
h.onreadystatechange @ sakura-app.js?ver=3.4.0:896
XMLHttpRequest.send (async)
d @ sakura-app.js?ver=3.4.0:898
loadMeting @ sakura-app.js?ver=3.4.0:910
live2d.min.js:1 Live2D 2.1.00_1
live2d.min.js:1 profile : Desktop
live2d.min.js:1   [PROFILE_NAME] = Desktop
live2d.min.js:1   [USE_ADJUST_TRANSLATION] = false
live2d.min.js:1   [USE_CACHED_POLYGON_IMAGE] = false
live2d.min.js:1   [EXPAND_W] = 2
waifu-tips.js:65 
waifu-tips.js:213 小不点 23-23 加载完成
fontawesome-webfont.woff2:1 Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
fontawesome-webfont.woff:1 Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
DevTools failed to load SourceMap: Could not load content for https://mihoyo.wiki/wp-content/themes/sakura/lib/typed.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
fontawesome-webfont.ttf:1 Failed to load resource: net::ERR_CONNECTION_TIMED_OUT

**Comment by mashirozx** [comment]
这个应该不是主题里面的，是插件hermit-x里面的资源

**Comment by mashirozx** [comment]
应该是把这个关掉就行了
<img width="491" alt="image" src="https://user-images.githubusercontent.com/16148054/170310831-84392819-9c2e-462b-989f-0337c852ad28.png">

**Comment by AdminXYZ666** [comment]
> 应该是把这个关掉就行了 <img alt="图片" width="491" src="https://user-images.githubusercontent.com/16148054/170310831-84392819-9c2e-462b-989f-0337c852ad28.png">

问题解决了，谢谢大佬
