### ISSUE TITLE
还会修缮next分支吗？

### ISSUE THREAD

**Issue by GuihongWang** [mashirozx/Sakura#293]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
想试试next 但是一大堆command列表 弄得云里雾里的

**Describe alternatives you've considered**
command的列表加上步骤（？）

**Additional context**
无

**Comment by mashirozx** [comment]
把装个项目clone到themes目录下，执行yarn build即可

**Comment by GuihongWang** [comment]
> 把装个项目clone到themes目录下，执行yarn build即可

但是我的博客托管在非vps上 只能电脑编译  最后上传ip库的时候出问题了（ftp只能上传10mb的文件 ip库是63m）


&旧版本的IP归属地显示IANA 怎么办
![Screenshot_20220608_154330.jpg](https://user-images.githubusercontent.com/57795156/172560762-75b467a2-74a9-4dca-ac3b-6e4ab6c89d12.jpg)

**Comment by GuihongWang** [comment]
> > 把装个项目clone到themes目录下，执行yarn build即可
> 
> 但是我的博客托管在非vps上 只能电脑编译  最后上传ip库的时候出问题了（ftp只能上传10mb的文件 ip库是63m）
> 
> 
> &旧版本的IP归属地显示IANA 怎么办
> ![Screenshot_20220608_154330.jpg](https://user-images.githubusercontent.com/57795156/172560762-75b467a2-74a9-4dca-ac3b-6e4ab6c89d12.jpg)

![Screenshot_20220608_175843.jpg](https://user-images.githubusercontent.com/57795156/172591921-142d10c0-10f4-4341-b476-cfb869e48fe5.jpg)![Screenshot_20220608_175851.jpg](https://user-images.githubusercontent.com/57795156/172591928-03d95594-f4b7-4c4f-bfc0-0fa79a7a203d.jpg)
引头
