### ISSUE TITLE
默认封面图改用随机图片

### ISSUE THREAD

**Issue by mashirozx** [mashirozx/Sakura#30]
固定图片似乎对其他主题换过来的人不友好

**Comment by mashirozx** [comment]
#24

**Comment by mashirozx** [comment]
https://github.com/mashirozx/Sakura/search?q=temp.png&unscoped_q=temp.png

**Comment by mashirozx** [comment]
https://github.com/mashirozx/Sakura/blob/cdd13c47844ab5027dc912674f22885f0f651e1d/inc/decorate.php#L33

**Comment by mashirozx** [comment]
close issue #29

**Comment by hifocus** [comment]
`temp.png` 这张图太大了 压缩下体即吧 （Photoshop 修改图片大小，TinyPNG 压缩下就行了）

**Comment by hifocus** [comment]
图片接口可以考虑 METO 的 Bing API 以及 Unsplash Source

**Comment by mashirozx** [comment]
自己替换一下文件夹里的原图就可以了

**Comment by hifocus** [comment]
。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。
