### ISSUE TITLE
更改登录/注册页面会一直重定向

### ISSUE THREAD

**Issue by ghost** [mashirozx/Sakura#311]
**描述问题**
更改登录/注册页面会一直重定向，无论是正确的登录页面还是错误的
**bug 重现步骤**
更改登录页面到https://xxxx.xxx/wp-admin/ 或 https://xxxx.xxx/wp-login.php
**系统信息**
 - （前端）操作系统: Windows 10
 - 浏览器: Microsoft Edge 110.0.1587.50
 - PHP 版本 7.4
 - WordPress 版本 6.1.1
 - Sakura 主题版本 3.4.0

**补充信息**
虽然可以通过删除主题文件的方式来修复，但是重复重现步骤仍然会一直重定向

**Comment by LittleArray** [comment]
浏览器打开登录页面,并按下F12打开开发者模式,把最顶层的loading删掉就行了,我也这个问题,现在用别的插件代替主题的登陆了

**Comment by ghost** [comment]
OK，解决了
