### ISSUE TITLE
QQ头像无法获取

### ISSUE THREAD

**Issue by mole9630** [mashirozx/Sakura#315]
**描述问题**
评论区昵称输入QQ号时，QQ头像无法获取到.

**系统信息**
 - （前端）操作系统: Windows 10
 - 浏览器: Edge
 - PHP 版本 7.3
 - WordPress 版本 5.7.10
 - Sakura 主题版本 3.4.0

**补充信息**

**Comment by smallxu038** [comment]
由于QQ更新了接口，你需要在 _Sakura/inc/classes/QQ.php_ 替换接口为 ”http://users.qzone.qq.com/fcg-bin/cgi_get_portrait.fcg?uins=“ ，不过这样可以修复头像获取，但是昵称会因为编码不正确而显示错误字符，目前测试了数种编码依然无法正确解码，需要其他大佬找到正确的编码格式。

**Comment by QQB-Roy** [comment]
这个似乎可以
https://api.qjqq.cn/api/qqinfo?qq=
来源：隔壁主题
https://github.com/mirai-mamori/Sakurairo/issues/856

**Comment by mole9630** [comment]
> 这个似乎可以 https://api.qjqq.cn/api/qqinfo?qq= 来源：隔壁主题 [mirai-mamori/Sakurairo#856](https://github.com/mirai-mamori/Sakurairo/issues/856)

这个api目前的确可用，十分感谢
