### ISSUE TITLE
live2d? maybe...

### ISSUE THREAD

**Issue by mashirozx** [mashirozx/Sakura#5]

**Comment by mashirozx** [comment]
@BlackXMO 可能是贴图资源加载不完整，要保证模型资源的访问速度

**Comment by mashirozx** [comment]
@BlackXMO 无损压缩一下贴图资源是个不错的选择

**Comment by chanshiyucx** [comment]
看来这个问题不是只有我遇到过~(⊙﹏⊙)

**Comment by mashirozx** [comment]
@chanshiyucx 哈哈哈，你的live2d.js用的是猫与向日葵的吗？

**Comment by BlackXMO** [comment]
基本是猫与向日葵改的嘛。我用的是那个WP版的插件。。作者说可能是动作文件问题 奇怪。。。
