### ISSUE TITLE
关于摘要字数限制的问题

### ISSUE THREAD

**Issue by MomentDerek** [mashirozx/Sakura#55]
主题内的摘要字数限制似乎是失效的（或者说只能限制英文？）
我重新写了一个……（萌新……好像没办法直接pull，是GitHub太复杂了吗）
在function.php的1278行
```
/**
 * 改进版摘要长度限制
 * by Moment
 * https://momincong.xyz
 * https://vidaima.com
 */
function cn_excerpt($output) {
	$output = mb_substr($output,0, 100);
	return $output;
}
add_filter('the_excerpt', 'cn_excerpt');
```
这个新函数需要安装mbstring的php扩展，因为使用了mb_substr()函数。

**Comment by mashirozx** [comment]
这个问题当时也困扰了我好久。。最后想出来的办法只有限制摘要容器高度（max-height）同时手动填写每篇文章的摘要。
你提供的办法很棒，下次更新会作为一个选项添加进去的。

**Comment by mashirozx** [comment]
https://www.jianshu.com/p/6f048ea1d4b8
