### ISSUE TITLE
Can’t use function return value in write context

### ISSUE THREAD

**Issue by mashirozx** [mashirozx/Sakura#56]
收到多条反馈 PHP 报错：

> Fatal error: Can’t use function return value in write context in /www/…/themes/Sakura/functions.php on line 1475

问题代码：
<https://github.com/mashirozx/Sakura/blob/master/functions.php#L1475>

据[文档](https://secure.php.net/manual/en/function.empty.php#refsect1-function.empty-changelog)说 PHP 5.5.0 以上 `empty()` 可以使用非变量的。

主题说明已经标注了需要 PHP 7.1＋

不清楚出问题的 PHP 版本都是多少？

**Comment by marlkiller** [comment]
php v5.4

if ( empty( akina_option('default_feature_image' )) ) {
这块异常

**Comment by marlkiller** [comment]
SELECT * 
FROM wp_options 
WHERE option_name = 'template' 
OR option_name = 'stylesheet' 
OR option_name = 'current_theme'; 


UPDATE wp_options SET option_value = 'twentynineteen' WHERE option_name = 'template'; 
UPDATE wp_options SET option_value = 'twentynineteen' WHERE option_name = 'stylesheet'; 
UPDATE wp_options SET option_value = 'twentynineteen' WHERE option_name = 'current_theme'; 

后台打不开的 可以 数据库强制修改主图
twentynineteen 是theme下的文件夹名字

**Comment by mashirozx** [comment]
请使用 PHP 7.1＋
