### ISSUE TITLE
使用中发现的问题

### ISSUE THREAD

**Issue by MuenYu** [mashirozx/Sakura#59]
1. 使用`切换主题`更换字体后刷新页面，在切换主题中，选中的字体不能回选

2. 文章页返回顶部会有闪动(仅限使用[toc]的情况)

3. 当使用nginx fastcgi_cache时，头部背景不能根据设备自适应

4. new！3.1.9去除wp statistics插件后无法使用时光轴归档

只要能解决头部figure的实时自适应即可

**Comment by mashirozx** [comment]
问题一会在下一版修复
问题二在[演示站](https://sakura.2heng.xin/)也出现吗？
问题三，自适应是通过css实现的，应该与nginx无关，建议header image尺寸为landscape（长方形，长边水平）

**Comment by MuenYu** [comment]
@mashirozx 
演示站也会出现同样问题，浏览器版本：chrome 73.0.3683.86
