### ISSUE TITLE
恢复数据库后主题设置被重置

### ISSUE THREAD

**Issue by HeXis-YS** [mashirozx/Sakura#60]
每次还原数据库备份之后主题设置都会被清除，需要重新设置

**Comment by mashirozx** [comment]
主题设置框架使用的是<https://github.com/devinsays/options-framework-theme>，可尝试到该项目中反馈~

**Comment by HeXis-YS** [comment]
去看了一眼，作者最后一次更新是3年前，而且有大量显然未被解决的Issue被无故关闭。看来这个框架的作者是弃坑了，反馈了也未必能解决。算了，就这样吧，不影响使用。
总之非常感谢！
