### ISSUE TITLE
使用主题后，CPU 和内存占用很多。

### ISSUE THREAD

**Issue by baichaohua** [mashirozx/Sakura#62]
亲爱的作者 您好

使用该主题之后，我的mac book pro 一直嗡嗡作响，很像是编译大项目的感觉。
看了一下，CPU 占了105%,后来降到 15 %，内存占了200多兆。如果同时再打开您的主页，那么CPU 还是会爆升至 100%以上，内存占用大概300兆以上。
请问 有没有什么办法优化一下呢？

**Comment by mashirozx** [comment]
感谢反馈。这本是我学习前端期间的练手项目，所以没有考虑过性能的问题。如果以后有机会重构的话，相信能大大提升使用体验。
