### ISSUE TITLE
safari浏览器适配有问题

### ISSUE THREAD

**Issue by lczalh** [mashirozx/Sakura#65]

**Comment by mashirozx** [comment]
具体？

**Comment by lczalh** [comment]
在苹果电脑上的safari浏览器 博客名称的最后一个字是在第二行。

**Comment by mashirozx** [comment]
我没有设备，无法在safari上测试。是否能提供一下问题的截图？

**Comment by ivampiresp** [comment]
苹果手机的safari也有点问题，左侧菜单栏点开直接是空白，需要点一下左侧菜单中任意一个地方才会显示出菜单内容

**Comment by Alan-yhq** [comment]
无法加载图片
[https://i.loli.net/2019/07/05/5d1eeaac2a3ea14611.png
](url)

**Comment by ChinCskw** [comment]
![WeChat Image_20190813213642](https://user-images.githubusercontent.com/39579967/62946027-7994e280-be12-11e9-8f94-f02c9955975e.jpg)
设备是IPAD 在IPAD和MAC上均有这个问题 不管是使用Safari还是chrome都会出现 使用文字logo就会这样

**Comment by mashirozx** [comment]
话说能顺便帮忙排查一下原因吗？我没有可以运行safari 的设备😵

**Comment by mashirozx** [comment]
> ![WeChat Image_20190813213642](https://user-images.githubusercontent.com/39579967/62946027-7994e280-be12-11e9-8f94-f02c9955975e.jpg)
> 设备是IPAD 在IPAD和MAC上均有这个问题 不管是使用Safari还是chrome都会出现 使用文字logo就会这样

The same issue with #114

**Comment by mashirozx** [comment]
如果没有更多反馈就暂时close了，随时可以reopen。
