### ISSUE TITLE
插件兼容性问题：WP Editor.md

### ISSUE THREAD

**Issue by HeXis-YS** [mashirozx/Sakura#66]
WP Editor.md（10.0.3）的代码高亮功能与主题的代码块冲突，会导致代码块显示异常。

**Comment by mashirozx** [comment]
关闭插件的代码高亮功能

**Comment by HeXis-YS** [comment]
试过了，已经把代码高亮所有的选项都关闭了。如果从主页进入文章显示没有问题。如果直接输入文章网址还是显示异常。
如果禁用WP Editor.md就没有问题（其实还是有，直接输网址进入会不显示行号）
↓开启插件
[![](https://i.loli.net/2019/04/02/5ca3324f18ca3.jpg)](https://i.loli.net/2019/04/02/5ca3324f18ca3.jpg)
↓关闭插件
[![](https://i.loli.net/2019/04/02/5ca332382f3e1.jpg)](https://i.loli.net/2019/04/02/5ca332382f3e1.jpg)

**Comment by Alan-yhq** [comment]
同样问题

**Comment by mashirozx** [comment]
禁用插件提供的所有前端代码高亮选项
![image](https://user-images.githubusercontent.com/16148054/56916148-d5995c80-6aea-11e9-88dc-47bae5459904.png)
主题已经有前端代码高亮的js库了，再引入PrismJS 的话会有冲突

**Comment by mashirozx** [comment]
> 禁用插件提供的所有前端代码高亮选项
> ![image](https://user-images.githubusercontent.com/16148054/56916148-d5995c80-6aea-11e9-88dc-47bae5459904.png)
> 主题已经有前端代码高亮的js库了，再引入PrismJS 的话会有冲突

主题依赖的仅是WP Editor.md插件的markdown转换器功能，该插件提供的其他任何前端功能都不建议启用（代码高亮、目录、latex、流程图等等，这些功能主题可能不兼容）

**Comment by HeXis-YS** [comment]
> > 禁用插件提供的所有前端代码高亮选项
> > ![image](https://user-images.githubusercontent.com/16148054/56916148-d5995c80-6aea-11e9-88dc-47bae5459904.png)
> > 主题已经有前端代码高亮的js库了，再引入PrismJS 的话会有冲突
> 
> 主题依赖的仅是WP Editor.md插件的markdown转换器功能，该插件提供的其他任何前端功能都不建议启用（代码高亮、目录、latex、流程图等等，这些功能主题可能不兼容）

设置一样。请问你的插件是什么版本的？
[![](https://i.loli.net/2019/04/30/5cc7cd3fcf5f4.jpg)](https://i.loli.net/2019/04/30/5cc7cd3fcf5f4.jpg)

**Comment by SamsonWan** [comment]
話説試過在文章中插入圖片和音樂嗎 我插入不了 想問問有沒有這樣的問題 如果沒有 我就知道是自己這邊的問題了。謝謝

**Comment by mashirozx** [comment]
> > > 禁用插件提供的所有前端代码高亮选项
> > > ![image](https://user-images.githubusercontent.com/16148054/56916148-d5995c80-6aea-11e9-88dc-47bae5459904.png)
> > > 主题已经有前端代码高亮的js库了，再引入PrismJS 的话会有冲突
> > 
> > 
> > 主题依赖的仅是WP Editor.md插件的markdown转换器功能，该插件提供的其他任何前端功能都不建议启用（代码高亮、目录、latex、流程图等等，这些功能主题可能不兼容）
> 
> 设置一样。请问你的插件是什么版本的？
> [![](https://camo.githubusercontent.com/9fd57d2458fb2180d5aaed5b60cd7aa6f5325fdd/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30342f33302f356363376364336663663566342e6a7067)](https://i.loli.net/2019/04/30/5cc7cd3fcf5f4.jpg)

插件是最新版的，方便发个网址过来看看吗

**Comment by lizhihao6** [comment]
前端 JS 高亮库是不是暂不支持 shell/bash ?

**Comment by lizhihao6** [comment]
> 前端 JS 高亮库是不是暂不支持 shell/bash ?

好吧看了highlight.js是支持的.....只不过 sudo service restart 本来就没有高亮...

**Comment by flylic** [comment]
> 話説試過在文章中插入圖片和音樂嗎 我插入不了 想問問有沒有這樣的問題 如果沒有 我就知道是自己這邊的問題了。謝謝

我也插入不了，手动插入的话音乐可以加载出来，但是无法播放。

`[hermit auto="1" loop="1" unexpand="1" fullheight="0"]netease_songs#:1341852473[/hermit]`

**Comment by HeXis-YS** [comment]
> > > > 禁用插件提供的所有前端代码高亮选项
> > > > ![image](https://user-images.githubusercontent.com/16148054/56916148-d5995c80-6aea-11e9-88dc-47bae5459904.png)
> > > > 主题已经有前端代码高亮的js库了，再引入PrismJS 的话会有冲突
> > > 
> > > 
> > > 主题依赖的仅是WP Editor.md插件的markdown转换器功能，该插件提供的其他任何前端功能都不建议启用（代码高亮、目录、latex、流程图等等，这些功能主题可能不兼容）
> > 
> > 
> > 设置一样。请问你的插件是什么版本的？
> > [![](https://camo.githubusercontent.com/9fd57d2458fb2180d5aaed5b60cd7aa6f5325fdd/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30342f33302f356363376364336663663566342e6a7067)](https://i.loli.net/2019/04/30/5cc7cd3fcf5f4.jpg)
> 
> 插件是最新版的，方便发个网址过来看看吗

非常抱歉，隔了很久才回复。你可以参考一下[这个链接](https://hexis.moe/2019/02/05/website-building-note/)，时好时坏，我也说不清是怎么触发的。
另外，我在WP Editor.md的Github页面下看到了作者的[停止维护通告](https://github.com/JaxsonWang/WP-Editor.md/issues/334)。所以这边有没有其他MarkDown编辑器适配的计划呢

**Comment by mashirozx** [comment]
Markdown的事情重构以后再考虑了，可能在主题里集成一个转换器吧 #99

**Comment by mashirozx** [comment]
话说那个Jetpack by WordPress.com插件好像也支持文章和评论的Markdown，你试试能用不？

**Comment by mashirozx** [comment]
Be free to reopen again 😄

**Comment by bengdan** [comment]
同样的设置 同样的问题
https://manji.tech/2021/10/24/%e6%b5%8b%e8%af%95markdown/?preview_id=5&preview_nonce=83a03b663c&post_format=standard&_thumbnail_id=-1&preview=true
