### ISSUE TITLE
强迫症的一丢丢建议~

### ISSUE THREAD

**Issue by Bathur** [mashirozx/Sakura#67]
有些自己动手**拙劣**修补了下下，有些不会弄~求大佬瞅一眼啊  
【感觉有些是蜜汁处理…但是确实奏效了…】
【太菜了……不好意思提交Pull requests……下面尽量讲清楚，大佬自行定夺】

- 踩坑向？
1. ~主题设置>基本设置>主题风格中选择的颜色不能应用于导航栏，导航栏还是默认的橙色。~  
【已解决，蜜汁处理，Autoptimize的css优化不要开启 或 从本地加载style.css】
2. ~前端切换主题功能跑到左下了…且……网页底端一整条都是它……~  
【已解决，蜜汁处理，Autoptimize的css优化不要开启 或 从本地加载style.css】
3. BUG？返回顶部的小喵，点了之后嗖一下上去会弹两下！标准模板站也是如此！  （文章页）
【这个我真不会修……】

- 功能优化建议（手动Pull requests向？）
1. 前端切换主题功能（右下的那个）的最后一个按钮（代码里的注释是Night）加载的图不够宽，1080p，16：9的屏幕下背景会重复显示。  
【以~菜鸡~（就是自己捣鼓的）方式解决，标准演示站也是如此，大佬考虑更新下那张图，或者改下代码…改成平铺啥的？这个本菜鸡是暴力解决的，我自己直接在代码里去掉了这个按钮】
2. 后端登录页面有些没有“汉化”完全，共Remember Me、Slide to Verificate、OK!三处  
【以~菜鸡~（就是自己捣鼓的）方式方式解决，标准演示站也是如此，大佬要不要考虑统一风格？这个本菜鸡直接改了function.php里的几个地方（769，772，784行）就汉化了，也不知道弄的对不对】
3. 后端登录页面（就wp自带的那个）中“注册”、“找回密码”、“登录”（就输入用户名、密码、做验证的那个div最底下的）这些个文字链接（可能？）错误的设置了背景图片为后端登录界面的Logo图。  
【以~菜鸡~（就是自己捣鼓的）方式方式解决，标准演示站也是如此，这个可能…算个bug吧？大佬要不要改下？这个本菜鸡是暴力解决的，我把Logo图上方留了点透明区域。】
4. 文章页面，CC4.0的分享协议可以弄成可选项嘛~  
【以~菜鸡~（就是自己捣鼓的）方式方式解决，标准演示站也是如此，这个…其实不一定大家都想CC4.0分享的，要不弄个选项？emmm这个我自己在代码里粗暴的注释掉了……不知道大佬的本意是不是让大家都分享哈~】
5. 第一屏不动时，导航栏能不能稍微有点背景呢，纯透明有时和网页背景混在一起看不清了
【以~菜鸡~（就是自己捣鼓的）方式方式解决，标准演示站也是如此，但是还是提议改一下下，这个动style.css的site-header就行，加个background-color: rgba(255, 255, 255, .5)即可~大佬觉得呢】
6. 导航栏二级菜单超过3个汉字就换行了？  
【以~菜鸡~（就是自己捣鼓的）方式方式解决，标准演示站情况**未知**（因为是英文），大佬你瞅一眼？我…先把二级菜单缩减到了三个字以内】

- 求教系列！
1. 导航栏每个菜单前的icon是…肿么弄得呀
2. ~大佬您站点的Logo位置的字肿么辣么好看~  
【在主题展示页的评论下找到了，CSS自定义字体？不过还是…再问一句吧（我真烦人，趴地）】
3. ~Live2D插件推荐接哪家的~  
【在历史issue中找到了，不过还是留下继续问一句~有更新的吗（我猜没有）】

打扰大佬了~您有空回一个吧~~~

**Comment by mashirozx** [comment]
> 有些自己动手**拙劣**修补了下下，有些不会弄~求大佬瞅一眼啊
> 【感觉有些是蜜汁处理…但是确实奏效了…】
> 【太菜了……不好意思提交Pull requests……下面尽量讲清楚，大佬自行定夺】
> 
> * 踩坑向？
> 
> 1. 主题设置>基本设置>主题风格中选择的颜色不能应用于导航栏，导航栏还是默认的橙色。
>    【已解决，蜜汁处理，Autoptimize的css优化不要开启 或 从本地加载style.css】
> 2. 前端切换主题功能跑到左下了…且……网页底端一整条都是它……
>    【已解决，蜜汁处理，Autoptimize的css优化不要开启 或 从本地加载style.css】
> 3. BUG？返回顶部的小喵，点了之后嗖一下上去会弹两下！标准模板站也是如此！  （文章页）
>    【这个我真不会修……】
这个我这边没有呀，能录个屏吗？

> 
> * 功能优化建议（手动Pull requests向？）
> 
> 1. 前端切换主题功能（右下的那个）的最后一个按钮（代码里的注释是Night）加载的图不够宽，1080p，16：9的屏幕下背景会重复显示。
好的，下次换个图片

>    【以菜鸡（就是自己捣鼓的）方式解决，标准演示站也是如此，大佬考虑更新下那张图，或者改下代码…改成平铺啥的？这个本菜鸡是暴力解决的，我自己直接在代码里去掉了这个按钮】
> 2. 后端登录页面有些没有“汉化”完全，共Remember Me、Slide to Verificate、OK!三处
英文逼格更高点呀（懒）

>    【以菜鸡（就是自己捣鼓的）方式方式解决，标准演示站也是如此，大佬要不要考虑统一风格？这个本菜鸡直接改了function.php里的几个地方（769，772，784行）就汉化了，也不知道弄的对不对】
> 3. 后端登录页面（就wp自带的那个）中“注册”、“找回密码”、“登录”（就输入用户名、密码、做验证的那个div最底下的）这些个文字链接（可能？）错误的设置了背景图片为后端登录界面的Logo图。
喵喵喵？我语文是体育老师教的，没太看懂

>    【以菜鸡（就是自己捣鼓的）方式方式解决，标准演示站也是如此，这个可能…算个bug吧？大佬要不要改下？这个本菜鸡是暴力解决的，我把Logo图上方留了点透明区域。】
> 4. 文章页面，CC4.0的分享协议可以弄成可选项嘛~
采纳，请期待下版

>    【以菜鸡（就是自己捣鼓的）方式方式解决，标准演示站也是如此，这个…其实不一定大家都想CC4.0分享的，要不弄个选项？emmm这个我自己在代码里粗暴的注释掉了……不知道大佬的本意是不是让大家都分享哈~】
> 5. 第一屏不动时，导航栏能不能稍微有点背景呢，纯透明有时和网页背景混在一起看不清了
全屏全景图更过瘾吧。。

>    【以菜鸡（就是自己捣鼓的）方式方式解决，标准演示站也是如此，但是还是提议改一下下，这个动style.css的site-header就行，加个background-color: rgba(255, 255, 255, .5)即可~大佬觉得呢】
> 6. 导航栏二级菜单超过3个汉字就换行了？
小case，下版优化

>    【以菜鸡（就是自己捣鼓的）方式方式解决，标准演示站情况**未知**（因为是英文），大佬你瞅一眼？我…先把二级菜单缩减到了三个字以内】
> 
> * 求教系列！
> 
> 1. 导航栏每个菜单前的icon是…肿么弄得呀
![image](https://user-images.githubusercontent.com/16148054/56457479-20f69100-63ae-11e9-8ede-5026eeaf0ff7.png)


> 2. 大佬您站点的Logo位置的字肿么辣么好看
拿去不谢<https://cloud.moezx.cc/Fonts/%E5%96%B5%E8%90%8C%E3%80%90%E8%87%AA%E7%94%A8%E3%80%91/>

>    【在主题展示页的评论下找到了，CSS自定义字体？不过还是…再问一句吧（我真烦人，趴地）】
> 3. Live2D插件推荐接哪家的
自己写的，非插件（就一个live2d.js，然后一句 `loadlive2d(ele, url)` 就行了呀）

>    【在历史issue中找到了，不过还是留下继续问一句~有更新的吗（我猜没有）】
> 
> 打扰大佬了~您有空回一个吧~~~

**Comment by Bathur** [comment]
活捉大佬！我来进一步反馈下~稍候哈

**Comment by Bathur** [comment]
> 这个我这边没有呀，能录个屏吗？

GIF，应该可以看出来吧，就，比如标题图会弹两次~
![BackToTopIssue](https://user-images.githubusercontent.com/44486218/56457592-a464b200-63af-11e9-99c2-3b4bc8611a3d.gif)

> 喵喵喵？我语文是体育老师教的，没太看懂

[https://sakura.2heng.xin/wp-login.php](url)
看这里，  
Register | Lost your password?  
Privacy Policy  
这些文字背后，是不是有错误的背景呢~

然后就是，感谢大佬赐教的啦！虽然很多问题都自己捯饬掉了~

最后，新版本直接用git更新的话~会失去自己捯饬的修改吗？

**Comment by mashirozx** [comment]
看起来好像是你的浏览器问题，换Chrome试试
logo修好了，那是上次别人的pr里面加的代码，当时没仔细看==

**Comment by Bathur** [comment]
> 看起来好像是你的浏览器问题，换Chrome试试

Chrome73.0.3683.103（64位最新版）也是一样哦~图就不重复截了

> logo修好了，那是上次别人的pr里面加的代码，当时没仔细看==

好哒~大佬辛苦
