### ISSUE TITLE
文章装饰图以及上一篇下一篇

### ISSUE THREAD

**Issue by wuyun521** [mashirozx/Sakura#68]
![Screenshot_2019-04-08-12-08-17-091_com android browser](https://user-images.githubusercontent.com/40681822/55698622-576cfd00-59f9-11e9-996d-39188525f665.png)

![Screenshot_2019-04-08-12-08-17-091_com android browser](https://user-images.githubusercontent.com/40681822/55698615-51771c00-59f9-11e9-908f-1f0488de687b.png)
文章装饰图以及上一篇下一篇希望也可以和文章特色图一样，可以调用随机图片API，等级为自定义特色图>API特色图>调用文章第一张图文章第一章图

**Comment by Bathur** [comment]
自己魔改下代码就好啦~

**Comment by wuyun521** [comment]
> 自己魔改下代码就好啦〜

自己是改好了，我这个算是个建议

**Comment by mashirozx** [comment]
看情况应该是没有设置上一篇和下一篇文章的装饰图？

**Comment by wuyun521** [comment]
jsdelivr好像是失效了

**Comment by mashirozx** [comment]
#70
