### ISSUE TITLE
PC端网站今天突然排版错乱，似乎是在线资源出问题了？

### ISSUE THREAD

**Issue by Ruikoto** [mashirozx/Sakura#70]
PC端网站今天突然排版错乱，似乎是在线资源出问题了，看了一下，https://2heng.xin/的页面也出现了类似的问题。

我的页面：https://ruikoto.pub/

**Comment by mashirozx** [comment]
jsDelivr中国节点的证书过期了
https://github.com/jsdelivr/jsdelivr/issues/18147

**Comment by hifocus** [comment]
> jsDelivr中国节点的证书过期了
> [jsdelivr/jsdelivr#18147](https://github.com/jsdelivr/jsdelivr/issues/18147)

这个时候，提供替代选项就尤为重要。https://github.com/hifocus/merger/issues/5

**Comment by Ruikoto** [comment]
> jsDelivr中国节点的证书过期了
> [jsdelivr/jsdelivr#18147](https://github.com/jsdelivr/jsdelivr/issues/18147)

那只能等他修了（崩溃）

**Comment by mashirozx** [comment]
@hifocus 有备用方案的呀![Screenshot_2019-04-20-13-47-41-506_com.android.chrome.png](https://i.loli.net/2019/04/20/5cbab2b1dc56f.png)

**Comment by abc1763613206** [comment]
在下次更新中能否加入一个自定义CDN地址的功能？               
已经因为这个自己用七牛建了个CDN

**Comment by Ruikoto** [comment]
> @hifocus 有替代选项的呀![Screenshot_2019-04-20-13-47-41-506_com.android.chrome.png](https://camo.githubusercontent.com/f7e4b27f7fe86d227ac6a53f348ab5beaf2d84ba/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30342f32302f356362616232623164633536662e706e67)

排版基本恢复正常了，但是某些图标之类的依然没有正常加载，还有网页底部的音乐播放器也出现了很奇怪的问题，这些是不是只能等待那边换证书了
