### ISSUE TITLE
文章特色图 bug鸭

### ISSUE THREAD

**Issue by samondlee** [mashirozx/Sakura#73]
楼主你好呀

为啥我的文章 上面的cover 和文章下面的 上一篇 下一篇 是黑色的没有cover鸭(文章特色图)

地址给你附上了

我没有填写特色图，使用的是本地随机的文章特色图，只有首页正常显示，文章页的上面和下面的 上一篇下一篇并不会显示

地址
http://wordpress.likeqi.cn/

**Comment by samondlee** [comment]
头部装饰图是不是这个选项鸭

我没点对勾鸭 默认的。。。

**Comment by samondlee** [comment]
哎呀我看到了，
能不能默认开启鸭，不想单独设置，。我好懒。。。


8. 文章页页首装饰图（Feature Image）
后台文章/页面编辑器中有一个设置特色图（Feature Image）的窗口，每篇文章/页面需要单独设置，没有设置时默认为空白。这不是 bug，因为并不是每篇文章都需要装饰图。

**Comment by samondlee** [comment]
特色图片能不能直接调用本地随机图鸭。。。。

**Comment by samondlee** [comment]
增加一个选项就好了呜呜呜

**Comment by samondlee** [comment]
![3](https://user-images.githubusercontent.com/8521327/56871592-c8c92a00-6a52-11e9-9400-9beb1503171e.PNG)
![1](https://user-images.githubusercontent.com/8521327/56871593-c961c080-6a52-11e9-83b9-ee159cc7f0b2.PNG)
![2](https://user-images.githubusercontent.com/8521327/56871594-c961c080-6a52-11e9-8409-6f13022ee7a9.PNG)
如图，在没有特色图设置的时候，不能调用自动特色图，是黑色的，真的有点丑。。。emmm
既然有本地随机图片为什么不用呢呜呜呜

**Comment by samondlee** [comment]
dalaodalao

怎么设置博客默认的背景图片鸭， 比方说要小星星 不想每次 让新访客都手动选择。

**Comment by samondlee** [comment]
选择背景图的方案由@mygoare 提供

在314行后面

checkBgImgCookie(); 的前面


增加setCookie("bgImgSetting", 'https://view.moezx.cc/images/2018/01/24/kyotoanimation.png', 30);

即可设置默认背景


==============================

就等不上传特色图在，文章里也能显示随机图就好了[doge]

**Comment by samondlee** [comment]
![1](https://user-images.githubusercontent.com/8521327/56908103-3bc8b400-6ad8-11e9-9cbf-5e939b9a67a0.PNG)
![2](https://user-images.githubusercontent.com/8521327/56908104-3c614a80-6ad8-11e9-8f1f-5a1303c3e0e8.PNG)
@mashirozx 新问题！还是关于特色图，如图所示!
在没有选择主题的时候，特色图可以全屏，选了主题之后特色图就变小了，强迫症表示有点儿难受2333
不知道可不可以全部都全屏。

等以后重构的时候也加个选项吧QAQ

**Comment by mashirozx** [comment]
> 选择背景图的方案由@mygoare 提供
> 
> 在314行后面
> 
> checkBgImgCookie(); 的前面
> 
> 增加setCookie("bgImgSetting", 'https://view.moezx.cc/images/2018/01/24/kyotoanimation.png', 30);
> 
> 即可设置默认背景
> 
> ==============================
> 
> 就等不上传特色图在，文章里也能显示随机特色图就好了[doge]

这是前端设置主题样式的，你这样设置cookie的话就无法记住用户之前选择过的样式了，如果你只是想改默认的背景图那么直接在css里面给body加个background就可以了呀

**Comment by samondlee** [comment]
> > 选择背景图的方案由@mygoare 提供
> > 在314行后面
> > checkBgImgCookie(); 的前面
> > 增加setCookie("bgImgSetting", 'https://view.moezx.cc/images/2018/01/24/kyotoanimation.png', 30);
> > 即可设置默认背景
> > ==============================
> > 就等不上传特色图在，文章里也能显示随机特色图就好了[doge]
> 
> 这是前端设置主题样式的，你这样设置cookie的话就无法记住用户之前选择过的样式了，如果你只是想改默认的背景图那么直接在css里面给body加个background就可以了呀

百度了下方法 设置好了[doge]

等大佬修复大黑框特色图2333
