### ISSUE TITLE
统计插件

### ISSUE THREAD

**Issue by 785823869** [mashirozx/Sakura#74]
为什么启用统计插件播放器就乱码了
![QQ截图20190429115653](https://user-images.githubusercontent.com/34834755/57177878-5a91c680-6e9b-11e9-9173-931de6eeff25.png)

**Comment by mashirozx** [comment]
统计插件应该和前端样式无关吧，显然你这个是某个css文件没有加载出来，网址可以放出来吗，我看看

**Comment by mashirozx** [comment]
最新版已不再依赖统计插件，可以关掉看看
