### ISSUE TITLE
文章导航失效

### ISSUE THREAD

**Issue by pcy190** [mashirozx/Sakura#75]
使用WP Editor.MD编写的markdown文章（就是经典编辑器），添加了`#TOC#`，生成的页面侧边没有文章导航。在主题设置中，已经将文章导航开启了。试过了`[TOC]`等等，都没有效果。
版本 Scilper v2.0.4
（我用Sakura也生成不了)
希望能根据markdown的#标题生成侧边可以跟动的文章导航目录。
![](https://user-images.githubusercontent.com/40729789/57219816-e2a6d600-702b-11e9-9d4b-9007bba755bc.png)
编辑器视角
![](https://user-images.githubusercontent.com/40729789/57219899-1255de00-702c-11e9-9467-8bbb4fd0fc6e.png)

**Comment by mashirozx** [comment]
文章任意位置放入`[toc]`几个字符就可以了，不要大写，不需要安装任何插件

**Comment by pcy190** [comment]
谢谢，it works~!

**Comment by pcy190** [comment]
我还想问一下固定链接把`inedx.php`去掉报404错误的问题。
如果我的链接中加了index.php就可以正常访问。
![](https://user-images.githubusercontent.com/40729789/57531457-19525880-736c-11e9-86e7-a1d737101735.png)
如果我把链接中的index.php去掉就会访问出现404错误。
![](https://user-images.githubusercontent.com/40729789/57531545-5fa7b780-736c-11e9-9703-05c72ef5d2c3.png)
类似`wordpress/%year%/%monthnum%/%day%/%postname%/`这样的链接都会404
（虽然这并不是主题的issue，但还是想问一下
我估计是apache的url rewrite的问题，但是一直解决不了
这是我wp根目录下面的htaccess文件
![](https://user-images.githubusercontent.com/40729789/57531747-bc0ad700-736c-11e9-9ede-3e5c61ce5d36.png)

我的环境：
apache2 , php7.0

非常感谢

**Comment by mashirozx** [comment]
应该是伪静态的问题，不过我不太了解Apache

**Comment by pcy190** [comment]
Yep , Thanks again .
