### ISSUE TITLE
文章目录跳转

### ISSUE THREAD

**Issue by bestinera** [mashirozx/Sakura#79]
点击右侧文章目录中的标题跳转。
标题显示在浏览器菜单栏的下方（浏览器可见部分最上方），不是在网站的分类目录导航栏的下方。
导致标题和文章部分内容被导航栏遮挡了。

版本是3.1.7

**Comment by SamsonWan** [comment]
同 剛想問 錨點跳轉的問題怎麽修復
![image](https://user-images.githubusercontent.com/33344352/59546235-9caf2d00-8f5c-11e9-9180-31808d18a41f.png)

**Comment by bestinera** [comment]
@SamsonWan 这是仅适用于本地vps解决标题跳转的办法
来源：从作者的博客代码中找的。
1在后台的主题设置启用：CDN——本地调用主题 js、css 文件.
2在主题根目录style.css中添加下面的css，可自行修改偏移量。
3清空浏览器数据。

h1[id*=toc-head]:before, h2[id*=toc-head]:before, h3[id*=toc-head]:before, h4[id*=toc-head]:before, h5[id*=toc-head]:before, h6[id*=toc-head]:before {
    display: block;
    content: " ";
    height: 80px;
    margin-top: -80px;
    visibility: hidden;
}

**Comment by SamsonWan** [comment]
ok  謝謝

**Comment by bestinera** [comment]
@SamsonWan 这你就得问作者了，我至今都不知道author页是什么，在哪里。应该是我没注意。
