### ISSUE TITLE
仪表盘自定义色彩模式等小缺陷

### ISSUE THREAD

**Issue by Bathur** [mashirozx/Sakura#83]
如图，在自定义色彩模式下，有些背景的半透明遮罩木有，或者不全~
![1](https://user-images.githubusercontent.com/44486218/59141547-8b58a480-89e1-11e9-8b13-c9a375580d4c.png)
![2](https://user-images.githubusercontent.com/44486218/59141549-8b58a480-89e1-11e9-8d57-589d6a53979b.png)
![3](https://user-images.githubusercontent.com/44486218/59141550-8bf13b00-89e1-11e9-943d-a1d1a18e2be2.png)

另，页面壁纸（背景？）Night~还是不能铺满全屏噻~

**Comment by mashirozx** [comment]
每个页面的Dom结构都不尽相同，所以需要加入相应的自定义样式
