### ISSUE TITLE
文章随机特色图实现非本地目录

### ISSUE THREAD

**Issue by Alan-yhq** [mashirozx/Sakura#84]
需要将图片提前标号后缀名一致，如pic-1.jpg，pic-2.jpg
进入feature/index.php
 
$img = rand(1,665);//这里填图片数量
$imgurl= "https://static.alanyhq.com/图床图片/pic-$img.jpg"; //懂得吧
if($imgurl) { 
	header("Location: " . $imgurl);//重定向
	exit();
} else {
	exit('error');
}

**Comment by Alan-yhq** [comment]
另外可以提供公共库本地化，需要博主支持

**Comment by Alan-yhq** [comment]
希望作者加上这个功能，因为有些时候web服务器的带宽不会太大

**Comment by spirit1431007** [comment]
我一直用的这个，不过每个人喜欢的图片类型不一样吧，公共库不现实，这个还是自建一个api好些~~

**Comment by Alan-yhq** [comment]
> 
> 
> 我一直用的这个，不过每个人喜欢的图片类型不一样吧，公共库不现实，这个还是自建一个api好些~~

我是指js这些资源，不是图片

**Comment by Alan-yhq** [comment]
> 
> 
> 我一直用的这个，不过每个人喜欢的图片类型不一样吧，公共库不现实，这个还是自建一个api好些~~

使用谷歌字体源的打开的时候会有很明显的卡顿感

**Comment by spirit1431007** [comment]
@Alan-yhq emmm...我感觉不出来，不过js css之类不是已经可以本地化了吗？（里面的小图除外，不过小图也比较容易替换啦

**Comment by Alan-yhq** [comment]
@spirit1431007 到自建CDN或者存储，就是类似于自定义CDN域名，我这里特别明显，打开文章会白一下子，然后文字一闪一闪的出现

**Comment by spirit1431007** [comment]
> @spirit1431007 到自建CDN或者存储，就是类似于自定义CDN域名，我这里特别明显，打开文章会白一下子，然后文字一闪一闪的出现

我清理了下缓存又去直连你的站点看了看，没有出现这种情况，可能不同地区的网络情况不同吧...

**Comment by Alan-yhq** [comment]
> > @spirit1431007 到自建CDN或者存储，就是类似于自定义CDN域名，我这里特别明显，打开文章会白一下子，然后文字一闪一闪的出现
> 
> 我清理了下缓存又去直连你的站点看了看，没有出现这种情况，可能不同地区的网络情况不同吧...

……可能吧，就是可不可以把文件全部路径打包好给我们用户，然后懂吧

**Comment by mashirozx** [comment]
feature image接口抽空我会改一下，做成和cover image一样的形式。至于文件打包什么的我一直没做就是因为懒:stuck_out_tongue_closed_eyes:

**Comment by Alan-yhq** [comment]
> feature image接口抽空我会改一下，做成和cover image一样的形式。至于文件打包什么的我一直没做就是因为懒😝

感谢……但是我觉得放在公共CDN不是一个长远的打算

**Comment by mashirozx** [comment]
https://github.com/mashirozx/Sakura/tree/dev/manifest#%E5%B0%81%E9%9D%A2%E5%9B%BE%E7%94%9F%E6%88%90%E5%B7%A5%E5%85%B7
