### ISSUE TITLE
無法在文章内插入音樂與圖片Console顯示Uncaught ReferenceError: wpActiveEditor is not defined 

### ISSUE THREAD

**Issue by SamsonWan** [mashirozx/Sakura#88]
無法在文章内插入音樂與圖片Console顯示Uncaught ReferenceError: wpActiveEditor is not defined

**Comment by SamsonWan** [comment]
![image](https://user-images.githubusercontent.com/33344352/59506045-d25f0200-8ed9-11e9-827b-1ce8c7b8fc6a.png)

**Comment by mashirozx** [comment]
这个 media-upload.min.js 是哪里的？如果是第三方插件那么这不是主题的问题

**Comment by SamsonWan** [comment]
> 这个 media-upload.min.js 是哪里的？如果是第三方插件那么这不是主题的问题
 
![微信图片_20190614203109](https://user-images.githubusercontent.com/33344352/59509344-5d90c580-8ee3-11e9-9f82-742e916ef96e.png)
![微信图片_201906142031091](https://user-images.githubusercontent.com/33344352/59509345-5d90c580-8ee3-11e9-8a15-ccdccd34d443.png)

沒有加   什麽插件  和這個backup的有關係嗎？ 我停用了也不行  。 謝謝

**Comment by SamsonWan** [comment]
![微信截图_20190614203344](https://user-images.githubusercontent.com/33344352/59509501-c1b38980-8ee3-11e9-8623-042c016ea7be.png)

**Comment by SamsonWan** [comment]
![微信截图_20190614204356](https://user-images.githubusercontent.com/33344352/59510001-2c18f980-8ee5-11e9-8b2a-368bea3a7fd7.png)
上傳音樂 是這樣的

**Comment by mashirozx** [comment]
看起来似乎是 wp-markdown.md 插件不接受外部传入的文字，所以如果继续使用这个插件，建议插图时使用 markdown 语法插入外链图片，插入音乐时可以复制你的截图最下面那段灰色背景的代码到编辑器上。

如果不习惯上面的方法，可以关掉 wp-markdown.md 插件，直接用 wordpress 自带的 gutenberg 编辑器。

![image](https://user-images.githubusercontent.com/16148054/59517249-b9644a00-8ef5-11e9-8831-b05f6557b5a1.png)
