### ISSUE TITLE
<img>标签不能带有class，否则图片一直在加载中

### ISSUE THREAD

**Issue by SkiTiSu** [mashirozx/Sakura#89]
正在把博客里的文章换成markdown，但是发现之前用wp图形化编辑器插入的图片，如
```html
<img class="alignnone size-full wp-image-604" src="xxx.jpg">
```
只要带有class，使用本主题后就会一直显示加载中的动画，需要完全删除class，如
```html
<img src="xxx.jpg">
```
才可以正常加载

**Comment by mashirozx** [comment]
并没有遇到你描述的问题

![image](https://user-images.githubusercontent.com/16148054/59518687-c0d92280-8ef8-11e9-8988-b207d5622ef8.png)

![image](https://user-images.githubusercontent.com/16148054/59518671-b6b72400-8ef8-11e9-8edc-e3a95f03ad97.png)

当然，如果你一定要在`<img>`里带class的话建议把functions.php第1514-1519行删掉：
![image](https://user-images.githubusercontent.com/16148054/59518867-3218d580-8ef9-11e9-8d45-63b32309cd05.png)

**Comment by SkiTiSu** [comment]
感谢回复~在我的博客环境中的确存在这样的现象，不过现在已经逐渐把一些老文章换成md了也就不存在这个问题了

加上两个class
![image](https://user-images.githubusercontent.com/8959735/59519196-e9155100-8ef9-11e9-9276-005d3964ea47.png)
全部删掉
![image](https://user-images.githubusercontent.com/8959735/59519286-1d890d00-8efa-11e9-9e89-73f44d3261e5.png)

**Comment by lizhihao6** [comment]
确实存在这个问题……为什么我把所有格preloader.svg都注释掉了还是不行

**Comment by spirit1431007** [comment]
> 确实存在这个问题……为什么我把所有格preloader.svg都注释掉了还是不行

重新改下[正则](https://github.com/mashirozx/Sakura/blob/47afa016b19999d2473ce5970c4674a3f474d432/functions.php#L1516)
试一下这个：
```
<img'.'$1'.'class=\"lazyload\" data-src=\"'.'$2'.'" src=\"https://cdn.jsdelivr.net/gh/moezx/cdn@3.0.2/img/svg/loader/trans.ajax-spinner-preloader.svg\" onerror=\"imgError(this)\"'.'$3'.' >\n<noscript>'.'$0'.'</noscript>
```

**Comment by spirit1431007** [comment]
@SkiTiSu @lizhihao6 使用[此处的正则](https://github.com/mashirozx/Sakura/issues/89#issuecomment-510076316)后是否还有这个问题？
