### ISSUE TITLE
能否在主题设置里增加隐藏首页登陆入口的选项？

### ISSUE THREAD

**Issue by Etren** [mashirozx/Sakura#90]
作为一个根本不懂编程的小白……
想隐藏首页登陆入口，
只能用笨办法注释掉了/themes/Sakura/header.php
line 109`<?php /*header_user_menu();*/ if(akina_option('top_search') == 'yes') { ?>`
（囧rz    鬼知道找到这个选项对一个完全不懂编程的小白有多困难！用审查元素折腾了好几个小时都没找到，最后没办法了，一行一行看header.php的代码才找到这个疑似`header_user_menu();`）
希望能在主题设置菜单里增加一个跟开启搜索按钮一样的选项可以用来隐藏登陆入口。

如果大神方便的话，能不能以主题设置菜单里开启/关闭搜索按钮为例子，讲一下怎么在源码里添加隐藏/显示登陆入口的选项啊。

**Comment by Etren** [comment]
还有一个小问题，主站的导航栏是怎么实现居中显示的呢？

**Comment by mashirozx** [comment]
不要注释PHP，直接注释HTML就行了（<!-xxx->）

**Comment by mashirozx** [comment]
导航栏居中改动比较多，懒得搬过来了。。:mask:

**Comment by Etren** [comment]
> 导航栏居中改动比较多，懒得搬过来了。。😷

哪里能找到有相关的代码啊？我自己研究研究。

**Comment by mashirozx** [comment]
header.php里导航栏结构需要调整，style.css里样式需要调整，可以f12抄一下我的博客
