### ISSUE TITLE
评论界面保存cookie复选框位置错误

### ISSUE THREAD

**Issue by Etren** [mashirozx/Sakura#91]
评论界面保存cookie的复选框位置错误，复选框没有显示在提示语开头，而是在提示语上一行居中显示。
换过chrome浏览器和搜狗浏览器还有edge浏览器都是这样。
![截图](https://github.com/Etren/image/blob/master/QQ%E6%88%AA%E5%9B%BE20190701015805.png?raw=true)

**Comment by mashirozx** [comment]
这个不是主题里的，请关闭第三方插件

**Comment by Etren** [comment]
> 这个不是主题里的，请关闭第三方插件

找到原因了，是主题没有启用复选框的自动宽度。
在“仪表盘→外观→自定义→额外CSS”中添加代码：
`input[type=checkbox] {
    width: auto;
}`
问题已解决！
