### ISSUE TITLE
大佬，在代码里面引号被转义成符号了

### ISSUE THREAD

**Issue by yqchilde** [mashirozx/Sakura#93]
大佬，在代码里面引号被转义成符号了有什么办法![image](https://user-images.githubusercontent.com/36953759/61060269-df193c00-a42c-11e9-9228-1fb8df98f4f2.png)

**Comment by mashirozx** [comment]
请问问题解决了吗

**Comment by yqchilde** [comment]
你好，已经解决，和wp统计插件冲突------------------ 原始邮件 ------------------
发件人: "Mashiro"<notifications@github.com>
发送时间: 2019年8月3日(星期六) 上午8:55
收件人: "mashirozx/Sakura"<Sakura@noreply.github.com>;
抄送: "yqchilde"<1455723643@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [mashirozx/Sakura] 大佬，在代码里面引号被转义成符号了 (#93)



请问问题解决了吗
 
&mdash;

**Comment by mashirozx** [comment]
wp-statistics？

**Comment by yqchilde** [comment]
是的，是这个插件------------------ 原始邮件 ------------------
发件人: "Mashiro"<notifications@github.com>
发送时间: 2019年8月3日(星期六) 上午9:12
收件人: "mashirozx/Sakura"<Sakura@noreply.github.com>;
抄送: "yqchilde"<1455723643@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [mashirozx/Sakura] 大佬，在代码里面引号被转义成符号了 (#93)



wp-statistics？
 
&mdash;

**Comment by mashirozx** [comment]
我一直在用这个插件没遇到过这样的问题。。。那我先close了

**Comment by mashirozx** [comment]
好像找到原因了，不是统计插件的问题，是因为你用了WordPress自带的Gutenberg编辑器吧？

<https://wordpress.stackexchange.com/questions/330596/wordpress-5-1-and-syntax-highlighter-problem-with-html-encoded-special-characte>

据问题下面的评论说使用代码高亮块（SyntaxHighlighter Code）而不是自定义HTML（Custom HTML）就可以了。

**Comment by yqchilde** [comment]
你好，我并没有用默认的古腾堡编辑器，用的markdowm的，插件名字叫“WP Githuber MD”

**Comment by yqchilde** [comment]
谢谢你提醒了我，我打开这款插件的git地址，看到了同款issue，这是这款插件的问题，不是统计插件的问题。

**Comment by mashirozx** [comment]
了解。还可以试试那个Jetpack by WordPress.com插件，里面有Markdown支持，很久以前用过，应该能兼容。

**Comment by yqchilde** [comment]
好的，辛苦了
