### ISSUE TITLE
各位了解一下作者的为人

### ISSUE THREAD

**Issue by SuzukiHonoka** [mashirozx/Sakura#98]
真是素质堪忧呢。
是是是我故意留的后门，来咬我呀

_Originally posted by @mashirozx in https://github.com/mashirozx/Sakura/issues/97#issuecomment-517676979_

**Comment by hifocus** [comment]
如果对主题有所怀疑，请找出相应的代码证明你自己的观点。

Sakura 是开源 Wordpress 主题，对代码没有加密。

**Comment by hifocus** [comment]
建议 Mashiro 直接举报滥用 + 屏蔽 + 删除无意义的 issue

**Comment by mashirozx** [comment]
![Screenshot_2019-08-02-20-23-09-096_com.android.chrome.png](https://i.loli.net/2019/08/02/5d442b47404db84468.png) ![Screenshot_2019-08-02-20-19-35-790_com.fastaccess.github.png](https://i.loli.net/2019/08/02/5d442b8f85ca896780.png)

![Screenshot_2019-08-02-20-23-09-096_com.android.chrome.png](https://i.loli.net/2019/08/02/5d442b47404db84468.png)

先学会看文档，先学会说人话，再来开issue。没本事别用。

**Comment by SuzukiHonoka** [comment]
完全按照您写的wiki做的。

**Comment by SuzukiHonoka** [comment]
> ![Screenshot_2019-08-02-20-23-09-096_com.android.chrome.png](https://camo.githubusercontent.com/12f20649b5b448c73a0f2223c69a582c2d885feb/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30382f30322f3564343432623437343034646238343436382e706e67) ![Screenshot_2019-08-02-20-19-35-790_com.fastaccess.github.png](https://camo.githubusercontent.com/a68ac42aef65acf66259c304affa1262b9e9e861/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30382f30322f3564343432623866383563613839363738302e706e67)
> 
> ![Screenshot_2019-08-02-20-23-09-096_com.android.chrome.png](https://camo.githubusercontent.com/12f20649b5b448c73a0f2223c69a582c2d885feb/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30382f30322f3564343432623437343034646238343436382e706e67)
> 
> 先学会看文档，先学会说人话，再来开issue。没本事别用。
完全按照您写的wiki做的。
最后还是使用rm -r来直接删除主题目录的。
您是要我重现一遍吗？

**Comment by mashirozx** [comment]
亲建议您 `rm -rf *` 呢

**Comment by SuzukiHonoka** [comment]
跟您没得说，自己做的东西有bug不承认，装清高可真牛。

**Comment by SuzukiHonoka** [comment]
> 亲建议您 `rm -rf *` 呢

像这种缺德的作者在GitHub上第一次见，我可祝您早日被fire。
