### ISSUE TITLE
主题重构事宜

### ISSUE THREAD

**Issue by mashirozx** [mashirozx/sakura#99]
作为一个两年前入坑时的练手项目，历史遗留的诸多漏洞、技术水平有限的情况下产生的大量不规范代码，使得项目难以维护，故决定重构。重构版正式发布之前，除非重大漏洞，在无现成 pull request 的情况下， Sakura v3 的细节问题不一定专门修复；如有新功能需求，会在重构版中予以考虑。
****
Update 2021:   
正在重构，预计今年7月中旬发布。  
Working on progress, the first release is estimated in the middle of this July.

**Comment by samondlee** [comment]
star666了 支持嗷

**Comment by mashirozx** [comment]
有人抢在我之前用React重写了，呜呜呜
https://github.com/byteblogs168/theme-react-sakura/

**Comment by samondlee** [comment]
> 有人抢在我之前用React重写了，呜呜呜
> https://github.com/byteblogs168/theme-react-sakura/

哈哈哈哈哈哈哈哈太草了，期待主题更新，这样会不会更省事儿
